### DISCUSSION TITLE
./kk artifact image push

### DISCUSSION THREAD

**Discussion by dianwei02** [kubesphere/kubesphere#6071] [General]
我不知道为什么kubekey离线部署不能使用私有仓库docker-distribution.service
[root@kubekey-test ~]# ./kk artifact image push -f config-sample.yaml -a kubesphere.tar.gz

 _   __      _          _   __
| | / /     | |        | | / /
| |/ / _   _| |__   ___| |/ /  ___ _   _
|    \| | | | '_ \ / _ \    \ / _ \ | | |
| |\  \ |_| | |_) |  __/ |\  \  __/ |_| |
\_| \_/\__,_|_.__/ \___\_| \_/\___|\__, |
                                    __/ |
                                   |___/

20:22:43 CST [UnArchiveArtifactModule] Check the KubeKey artifact md5 value
20:22:44 CST success: [LocalHost]
20:22:44 CST [UnArchiveArtifactModule] UnArchive the KubeKey artifact
20:22:44 CST skipped: [LocalHost]
20:22:44 CST [UnArchiveArtifactModule] Create the KubeKey artifact Md5 file
20:22:44 CST skipped: [LocalHost]
20:22:44 CST [CopyImagesToRegistryModule] Copy images to a private registry from an artifact OCI Path
20:22:44 CST Source: oci:/root/kubekey/images:kubesphereio:cni:v3.26.1-arm64
20:22:44 CST Destination: docker://172.17.50.17:5000/kubesphereio/cni:v3.26.1-arm64
Getting image source signatures
Getting image source signatures
Getting image source signatures
Getting image source signatures
Getting image source signatures
20:22:44 CST success: [LocalHost]
20:22:44 CST [CopyImagesToRegistryModule] Push multi-arch manifest to private registry
20:22:44 CST message: [LocalHost]
get manifest list failed by module cache
20:22:44 CST failed: [LocalHost]
error: Pipeline[ArtifactImagesPushPipeline] execute failed: Module[CopyImagesToRegistryModule] exec failed:
failed: [LocalHost] [PushManifest] exec failed after 1 retries: get manifest list failed by module cache

配置信息
```
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: kubekey-test, address: 172.17.50.19, internalAddress: 172.17.50.19, user: root, password: "authing@123", arch: arm64}
  roleGroups:
    etcd:
    - kubekey-test
    control-plane:
    - kubekey-test
    worker:
    - kubekey-test
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    # internalLoadbalancer: haproxy

    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.24.8
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    multusCNI:
      enabled: false
  registry:
    auths:
      "172.17.50.17:5000":
        skipTLSVerify: false
        plainHTTP: false
    privateRegistry: "172.17.50.17:5000"
    namespaceOverride: "kubesphereio"
    registryMirrors: []
    insecureRegistries: []
  addons: []
```
