### ISSUE TITLE
灰度发布错误

### ISSUE THREAD

**Issue by Carriezhangyan** [kubesphere/kubesphere#1481]
自己写了一个yaml文件，创建灰度发布的任务组件，，但是登陆kubesphere的浏览器界面，在创建的项目中，创建灰度发布的任务组件中没有找到写的那个组件，，不知道可能是什么原因？帮忙分析一下吧

部分代码如下：
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: angel-web-v1
  namespace: crm-dev
  labels:
    app: angel-web
    app.kubernetes.io/name: angel-web
    app.kubernetes.io/version: v1
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '2'
    kubesphere.io/isElasticReplicas: 'false'
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angel-web
      app.kubernetes.io/name: angel-web
      app.kubernetes.io/version: v1
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: angel-web
        app.kubernetes.io/name: angel-web
        app.kubernetes.io/version: v1
        version: v1
      annotations:
        kubesphere.io/containerSecrets: '{"angel-web":"regcred"}'
        sidecar.istio.io/inject: 'true'
```

但是没有找到组件
![微信截图_20191113105535](https://user-images.githubusercontent.com/46554638/68729169-30685080-0604-11ea-96c0-1962d406217c.png)
