### ISSUE TITLE
点击项目 有报错 无法通过应用商店部署

### ISSUE THREAD

**Issue by wanghonglei5181** [kubesphere/kubesphere#1640]
```
错误信息  点击项目 查看项目信息右上角的提示信息如下：
Internal Server Error
rpc error: code = Internal desc = describe resources failed: Error 1146: Table 'cluster.cluster' doesn't exist
```
```
ks版本2.1.0
系统版本centos6.5 64bit
```
```
kubectl logs ks-apigateway-65dd54f989-687xj --tail 10 -f 
有http500错误
10.233.70.21 06/Dec/2019:02:26:18 +0000 POST /kapis/openpitrix.io/v1/namespaces/mytest/applications HTTP/1.1 500 126 284ms
```
![微信图片_20191206110054](https://user-images.githubusercontent.com/8133524/70292071-fa3f7a80-1817-11ea-92e1-ae62fe373f30.png)
![微信图片_20191206105638](https://user-images.githubusercontent.com/8133524/70292104-16dbb280-1818-11ea-89a3-0f3330f05fd7.png)

**Comment by wansir** [comment]
/kind bug
/milestones 2.1.1
/assign @pengcong06 

Even if the database init job is completed status, the database may still have no tables.

> The db init job will retry 6 times after MySQL is started

```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
  ...
  name: openpitrix-db-init-job
  namespace: openpitrix-system
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: openpitrix-db-init
    spec:
      containers:
      ...
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z mysqll.kubesphere-system.svc 3306; do echo "waiting for mysql";
          sleep 2; done;
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        name: wait-mysql
      restartPolicy: OnFailure
```

**Comment by wanghonglei5181** [comment]
how to recreate the tables，thx！

**Comment by wansir** [comment]
rerun the db init jobs

```
for job in `kubectl -n openpitrix-system get job -o jsonpath="{.items[*].metadata.name}"`; do kubectl -n openpitrix-system get job $job -o json | jq 'del(.spec.selector)' | jq 'del(.spec.template.metadata.labels)' | kubectl replace --force -f -; done
```

**Comment by wanghonglei5181** [comment]
I have fixed this issue！
```
first:
kubectl edit cm -n kubesphere-system ks-installer
openpitrix:
      enabled: **True**   //modify true to false
second:
kubectl edit cm -n kubesphere-system ks-installer
openpitrix:
      enabled: **False**   //modify true to True
```
```
let openprix to recreate!!!
```
