### ISSUE TITLE
devops中ks-jenkins pod安装异常,VolumeBindingFailed

### ISSUE THREAD

**Issue by yingmingzongyu** [kubesphere/kubesphere#1683]
**问题描述**
我是在vmware中安装centos7.5系统，然后all-in-one 最小方式安装kubesphere 2.1在线版本。然后安装openpitrix、monitor、devops组件。不过现在devops中ks-jenkins、ks-jenkins-agent状态异常。pod显示：VolumeBindingFailed     事件：timed out waiting for the condition

**安装环境的硬件配置**
centos7.5 系统，4C14G150G配置。
ks-jenkins组件配置信息：
```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ks-jenkins
  namespace: kubesphere-devops-system
  labels:
    chart: jenkins-0.19.0
    component: ks-jenkins-jenkins-master
    heritage: Tiller
    release: ks-jenkins
  annotations:
    deployment.kubernetes.io/revision: '9'
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ks-jenkins-jenkins-master
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ks-jenkins
        chart: jenkins-0.19.0
        component: ks-jenkins-jenkins-master
        heritage: Tiller
        release: ks-jenkins
      annotations:
        checksum/config: 08e30096a520d2833ad39f8d009315185cec448db3bfb329ed95217650520bcb
    spec:
      volumes:
        - name: casc-config
          configMap:
            name: jenkins-casc-config
            defaultMode: 420
        - name: jenkins-config
          configMap:
            name: ks-jenkins
            defaultMode: 420
        - name: plugin-dir
          emptyDir: {}
        - name: secrets-dir
          emptyDir: {}
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: ks-jenkins
      initContainers:
        - name: copy-default-config
          image: 'jenkins/jenkins:2.176.2'
          command:
            - sh
            - /var/jenkins_config/apply_config.sh
          env:
            - name: JENKINS_UC_DOWNLOAD
              value: 'http://uc-jenkins-update-center'
          resources:
            limits:
              cpu: '1'
              memory: 8Gi
            requests:
              cpu: 500m
              memory: 4Gi
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-config
              mountPath: /var/jenkins_config
            - name: plugin-dir
              mountPath: /var/jenkins_plugins
            - name: secrets-dir
              mountPath: /usr/share/jenkins/ref/secrets/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: ks-jenkins
          image: 'jenkins/jenkins:2.176.2'
          args:
            - '--argumentsRealm.passwd.$(ADMIN_USER)=$(ADMIN_PASSWORD)'
            - '--argumentsRealm.roles.$(ADMIN_USER)=admin'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: slavelistener
              containerPort: 50000
              protocol: TCP
          env:
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xms3g -Xmx6g -XX:MaxRAM=8g
                -Dhudson.slaves.NodeProvisioner.initialDelay=20
                -Dhudson.slaves.NodeProvisioner.MARGIN=50
                -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85
                -Dhudson.model.LoadStatistics.clock=5000
                -Dhudson.model.LoadStatistics.decay=0.2
                -Dhudson.slaves.NodeProvisioner.recurrencePeriod=5000
                -verbose:gc -Xloggc:/var/jenkins_home/gc-%t.log
                -XX:NumberOfGCLogFiles=2 -XX:+UseGCLogFileRotation
                -XX:GCLogFileSize=100m -XX:+PrintGC -XX:+PrintGCDateStamps
                -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintGCCause
                -XX:+PrintTenuringDistribution -XX:+PrintReferenceGC
                -XX:+PrintAdaptiveSizePolicy -XX:+UseG1GC
                -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled
                -XX:+DisableExplicitGC -XX:+UnlockDiagnosticVMOptions
                -XX:+UnlockExperimentalVMOptions 
            - name: JENKINS_OPTS
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ks-jenkins
                  key: jenkins-admin-password
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: ks-jenkins
                  key: jenkins-admin-user
            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_home/casc_configs/jenkins.yaml
            - name: com.sun.jndi.ldap.connect.timeout
              value: '15000'
            - name: com.sun.jndi.ldap.read.timeout
              value: '60000'
            - name: kubernetes.connection.timeout
              value: '60000'
            - name: kubernetes.request.timeout
              value: '60000'
            - name: EMAIL_SMTP_HOST
              value: mail.example.com
            - name: EMAIL_SMTP_PORT
              value: '465'
            - name: EMAIL_USE_SSL
              value: 'False'
            - name: EMAIL_FROM_NAME
              value: KubeSphere
            - name: EMAIL_FROM_ADDR
              value: admin@example.com
            - name: EMAIL_FROM_PASS
              value: P@ssw0rd
          resources:
            limits:
              cpu: '1'
              memory: 8Gi
            requests:
              cpu: 500m
              memory: 4Gi
          volumeMounts:
            - name: casc-config
              readOnly: true
              mountPath: /var/jenkins_home/casc_configs
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: jenkins-config
              readOnly: true
              mountPath: /var/jenkins_config
            - name: plugin-dir
              mountPath: /usr/share/jenkins/ref/plugins/
            - name: secrets-dir
              mountPath: /usr/share/jenkins/ref/secrets/
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: ks-jenkins
      serviceAccount: ks-jenkins
      securityContext:
        runAsUser: 0
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```
