### ISSUE TITLE
devops 发布流程提示拉取镜像需要 `docker login` 

### ISSUE THREAD

**Issue by weiliang-ms** [kubesphere/kubesphere#1765]
deployment文件内容
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: zuul
    component: golf-zuul-dev
    tier: backend
  name: golf-zuul-dev
  namespace: golf-cloud-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: zuul
      component: golf-zuul-dev
      tier: backend
  template:
    metadata:
      labels:
        app: zuul
        component: golf-zuul-dev
        tier: backend
    spec:
      containers:
        - env:
            - name: CACHE_IGNORE
              value: js|html
            - name: CACHE_PUBLIC_EXPIRATION
              value: 3d
          image: harbor.weiliang.com/zuul/zuul:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          name: ks-zuul
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```

jenkinsfile

```
pipeline {
  agent {
    node {
      label 'maven'
    }
  }

    environment {
        HARBOR_CREDENTIAL_ID = 'harbor-id'
        GITLAB_CREDENTIAL_ID = 'gitlab-id'
        KUBECONFIG_CREDENTIAL_ID = 'demo-kubeconfig'
        REGISTRY = 'harbor.weiliang.com'
        HARBOR_NAMESPACE = 'zuul'
        GITLAB_ACCOUNT = 'weiliang'
        APP_NAME = 'zuul'
        SONAR_CREDENTIAL_ID= 'sonar-token'
    }

    stages {
        stage ('checkout scm') {
            steps {
                checkout(scm)
            }
        }

        stage ('unit test') {
            steps {
                container ('maven') {
                    sh 'mvn clean -gs `pwd`/settings.xml test'
                }
            }
        }

        stage('sonarqube analysis') {
          steps {
            container ('maven') {
              withCredentials([string(credentialsId: "$SONAR_CREDENTIAL_ID", variable: 'SONAR_TOKEN')]) {
                withSonarQubeEnv('sonar') {
                 sh "mvn sonar:sonar -gs `pwd`/settings.xml -Dsonar.branch=$BRANCH_NAME -Dsonar.login=$SONAR_TOKEN"
                }
              }
              timeout(time: 1, unit: 'HOURS') {
                waitForQualityGate abortPipeline: true
              }
            }
          }
        }

        stage ('build & push') {
            steps {
                container ('maven') {
                    sh 'mvn -Dmaven.test.skip=true -gs `pwd`/settings.xml clean package'
                    sh 'docker build -f Dockerfile -t $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER .'
                    withCredentials([usernamePassword(passwordVariable : 'DOCKER_PASSWORD' ,usernameVariable : 'DOCKER_USERNAME' ,credentialsId : "$HARBOR_CREDENTIAL_ID" ,)]) {
                        sh 'echo "$DOCKER_PASSWORD" | docker login $REGISTRY -u "$DOCKER_USERNAME" --password-stdin'
                        sh 'docker push  $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER'
                    }
                }
            }
        }

        stage('push latest'){
           when{
             branch 'master'
           }
           steps{
                container ('maven') {
                  sh 'docker tag  $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:latest '
                  sh 'docker push  $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:latest '
                }
           }
        }

        stage('deploy to dev') {
          when{
            branch 'master'
          }
          steps {
            input(id: 'deploy-to-dev', message: 'deploy to dev?')
            kubernetesDeploy(configs: 'deploy/dev/**', enableConfigSubstitution: true, kubeconfigId: "$KUBECONFIG_CREDENTIAL_ID")
          }
        }
    }
}

```
pod状态

```
Normal   Scheduled  5m45s                  default-scheduler  Successfully assigned golf-cloud-dev/golf-zuul-dev-794f6f996c-ft57g to work4
  Normal   Pulling    4m24s (x4 over 5m45s)  kubelet, work4     Pulling image "harbor.weiliang.com/zuul/zuul:SNAPSHOT-master-7"
  Warning  Failed     4m24s (x4 over 5m44s)  kubelet, work4     Failed to pull image "harbor.weiliang.com/zuul/zuul:SNAPSHOT-master-7": rpc error: code = Unknown desc = Error response from daemon: pull access denied for harbor.weiliang.com/zuul/zuul, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed     4m24s (x4 over 5m44s)  kubelet, work4     Error: ErrImagePull
  Warning  Failed     4m (x6 over 5m43s)     kubelet, work4     Error: ImagePullBackOff
  Normal   BackOff    38s (x20 over 5m43s)   kubelet, work4     Back-off pulling image "harbor.neusoft.com/zuul/zuul:SNAPSHOT-master-7"
```
pipeline

![image](https://user-images.githubusercontent.com/18642754/72324019-fd663a00-36e4-11ea-8a82-d2f64d15fd6a.png)

应该不需要手动配置harbor secret吧？

**Comment by soulseen** [comment]
拉取私有镜像是需要配置secret的，

**Comment by weiliang-ms** [comment]
修改项目中的deployment yaml文件，配置拉取镜像的secret还是提示没有权限
![image](https://user-images.githubusercontent.com/18642754/72419874-9e71f500-37b8-11ea-8692-2ff43c2d35f8.png)

执行以下命令查看配置，发现修改内容并没有生效

`kubectl get deployments -n golf-cloud-dev golf-zuul-dev -o yaml`

配置没有生效
![image](https://user-images.githubusercontent.com/18642754/72420332-8058c480-37b9-11ea-94fa-831cd491a5be.png)

请问是我操作的问题吗？

**Comment by soulseen** [comment]
deploy yaml中配置了secret吗，可以把更新后贴出来看下吗，上面的deployment截图中没有看到secret。可以在检查下，部署的deployment yaml文件。

**Comment by weiliang-ms** [comment]
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: zuul
    component: golf-zuul-dev
    tier: backend
  name: golf-zuul-dev
  namespace: golf-cloud-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: zuul
      component: golf-zuul-dev
      tier: backend
  template:
    metadata:
      labels:
        app: zuul
        component: golf-zuul-dev
        tier: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - env:
            - name: CACHE_IGNORE
              value: js|html
            - name: CACHE_PUBLIC_EXPIRATION
              value: 3d
          image: harbor.weiliang.com/zuul/zuul:SNAPSHOT-$BRANCH_NAME-$BUILD_NUMBER
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            timeoutSeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          imagePullPolicy: Always
          name: ks-zuul
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 1
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
```
