### ISSUE TITLE
Support extended-resource assignment to a Container

### ISSUE THREAD

**Issue by eliaskoromilas** [kubesphere/kubesphere#1851]
### Discussion

[https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/#discussion](https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/#discussion)

> Extended resources are opaque to Kubernetes; Kubernetes does not know anything about what they are. Kubernetes knows only that a Node has a certain number of them. Extended resources must be advertised in **integer amounts**. 

### Assign an extended resource to a Container

[https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource](https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource)

> To request an extended resource, include the `resources:requests` field in your Container manifest. Extended resources are fully qualified with any domain outside of `*.kubernetes.io/.` Valid extended resource names have the form `example.com/foo` where `example.com` is replaced with your organization’s domain and foo is a descriptive resource name.

### Example

![kubesphere_extended_resources](https://user-images.githubusercontent.com/24586902/74318931-c5efb980-4d86-11ea-95dc-91505fa533cd.png)

The above settings must result to the following YAML configuration:

```
resources:
  requests:
    cpu: '0.01'
    memory: 10Mi
    xilinx/u200: 2
    intel/pac_a10: 1
  limits:
    memory: 4000Mi
    xilinx/u200: 2
    intel/pac_a10: 1
```
