### ISSUE TITLE
The number of build images shown in the project overview is incorrect

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2490]
**Describe the Bug**
The number of build images shown in the project overview is incorrect
<img width="918" alt="build image" src="https://user-images.githubusercontent.com/36271543/87911831-d70fc580-ca9e-11ea-8512-7938ee6dbb99.png">

**Versions Used**
KubeSphere:3.0.0
Kubernetes:
host-v1.18.5
member1-v1.17.8

**Environment**
host: 3node /ubuntu 16.04 4cpu/16g
member1: 2 nodes /centos7 8cpu/16g

/kind bug
/area console
/assign @leoendless 
/milestone 3.0.0
/priority medium

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/87914619-7cc53380-caa3-11ea-9c8a-37771fe7de15.png)

[GET] kapis/clusters/shire/resources.kubesphere.io/v1alpha2/namespaces/harry-project001/quotas

return the wrong data

**Comment by huanggze** [comment]
plz have a look at this issue. s2ibuilders crd is not a part of k8s resource quota.
/cc @zryfish

**Comment by zryfish** [comment]
Since v1.15, kubernetes supports CRD resource quota, we can s2ibuilders resourcequota like following
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq
  namespace: p1
spec:
  hard:
    count/s2ibuilders.devops.kubesphere.io: "10"
status:
  hard:
    count/s2ibuilders.devops.kubesphere.io: "10"
  used:
    count/s2ibuilders.devops.kubesphere.io: "1"
```

@leoendless I think we should add s2ibuilders/s2iruns to our project resource quota list
