### ISSUE TITLE
Adjust Storage Capability by hand

### ISSUE THREAD

**Issue by min-zh** [kubesphere/kubesphere#2986]
In KubeSphere 3.0.0. , we designed `StorageCapability` to get the supported features of storage plugins. 
Features mainly include:
1. volume cloning
2. volume expanding
3. volume snapshot

Storage Plugins include:
1.  CSI plugin
2.  intree plugin
3. some other plugin. 

Realization of `StorageCapability` are different for CSI plugin and non-CSI plugin.

In CSI plugin, we call the CSI GPRC interface to get the `surpported feature`. 

In non-CSI plugin, we input the plugins' capability (maybe from K8s doc or the plugins' doc)  into Kubernetes. 

But sometimes, some CSI plugin are special realized so that KubeSphere can't call the GRPC interface.  Or you want to 
input some new non-CSI plugins' capability.  You could edit the ProvisionerCapability by hand to let KubeSphere know the
supported featrure.  For example, ceph-csi-rbd's ProvisionerCapability is: 

```
apiVersion: storage.kubesphere.io/v1alpha1
kind: ProvisionerCapability
metadata:
  name: rbd-csi-ceph-com
spec:
  pluginInfo:
    name: rbd.csi.ceph.com
    version: ""
  features:
    topology: false
    volume:
      create: true
      attach: false
      clone: true
      list: false
      stats: true
      expandMode: ONLINE
    snapshot:
      create: true
      list: false
```

The name Must be the Provisioner of the plugin( replace **.** to **-** ).  In the case of ceph-csi-rbd,  the provisioner of 
the plugin is `rbd.csi.ceph.com`, so the name of ProvisionerCapability is `rbd-csi-ceph-com`

`spec.features.clone`: = true,  means the plugin support volume cloning
`spec.features.expandMode`: = ONLINE or OFFLINE,  means the plugin support volume expanding online or offline,
 `spec.features.snapshot.create`: = true,  means the plugin support volume snapshot.

More information, see the [design documents](https://github.com/kubesphere/community/blob/master/sig-storage/concepts-and-designs/storage-capability-interface.md)
