### ISSUE TITLE
OAuth2 Identity Provider：GitHub authentication failed

### ISSUE THREAD

**Issue by fukiki** [kubesphere/kubesphere#3215]
**Describe the Bug**
Config `GitHubIdentityProvider` follow the document [OAuth2 Identity Provider](https://kubesphere.io/zh/docs/access-control-and-account-management/oauth2/), and login with github user,  login failed and error is `Not Found`.

**Versions Used**

- KubeSphere: master branch,commit id `d814d5db7bde49b44b31ad8ddf14da5517bc0c78`
- Kubernetes: 1.17.9

**Environment**
How many nodes and their hardware configuration:

CentOS 7
- 1 masters:  8cpu/8g; 
- 2 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Edit configMap kubesphere-config：`kubectl -n kubesphere-system edit cm kubesphere-config`
```yaml
apiVersion: v1
data:
  kubesphere.yaml: |
    authentication:
      authenticateRateLimiterMaxTries: 10
      authenticateRateLimiterDuration: 10m0s
      loginHistoryRetentionPeriod: 168h
      maximumClockSkew: 10s
      multipleLogin: True
      kubectlImage: kubesphere/kubectl:v1.0.0
      jwtSecret: "*********"
      oauthOptions:
        accessTokenMaxAge: 1h
        accessTokenInactivityTimeout: 30m
        identityProviders:
        - name: github
          type: GitHubIdentityProvider
          mappingMethod: auto
          provider:
            clientID: '14***c6'
            clientSecret: '55***4d'
            endpoint:
              authURL: 'https://github.com/login/oauth/authorize'
              tokenURL: 'https://github.com/login/oauth/access_token'
            redirectURL: 'http://***:30880/oauth/redirect'
            scopes:
            - user
```
2. Restart ks-apiserver: `kubectl -n kubesphere-system rollout restart deploy ks-apiserver`.
3. Visit `http://***:30880/login`, click on 'Log in with github'
4. See error : `Not Found`
5. The logs of ks-apiserver is as follows:
```
E1221 15:15:31.322326   99866 login_recoder.go:71] LoginRecord.iam.kubesphere.io "system:pre-registration-j44dc" is invalid: [metadata.generateName: Invalid value: "system:pre-registration-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "system:pre-registration-j44dc": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "system:pre-registration": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
E1221 15:15:31.322368   99866 handler.go:198] Failed to record successful login for user system:pre-registration, error: LoginRecord.iam.kubesphere.io "system:pre-registration-j44dc" is invalid: [metadata.generateName: Invalid value: "system:pre-registration-": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "system:pre-registration-j44dc": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.labels: Invalid value: "system:pre-registration": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]
```

**Expected behavior**
Click on 'Log in with github', login successfully.
