### ISSUE TITLE
Sidecar management

### ISSUE THREAD

**Issue by zryfish** [kubesphere/kubesphere#3299]
**What's it about and why we need it?**
[Sidecar](https://kubernetes.io/docs/concepts/workloads/pods/#using-pods) is a separate container that sits aside the main container inside a pod. Sidecar can be used in logging, monitoring, and is widely used by Istio. Since K8s v1.18, container can be specific created as a sidecar by adding `lifecyle`.
```
apiVersion: v1
kind: Pod
metadata:
  name: bookings-v1-b54bc7c9c-v42f6
  labels:
    app: demoapp
spec:
  containers:
  - name: bookings
    image: banzaicloud/allspark:0.1.1
    ...
  - name: istio-proxy
    image: docker.io/istio/proxyv2:1.4.3
    lifecycle:
      type: Sidecar
    ...
```

Hence, I think we need a better way to organize all these sidecar containers.

**Area Suggestion**

/area api
/kind feature-request
