### ISSUE TITLE
Can't sign in with Google Account

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3418]
**Describe the Bug**

After I configured OIDC Identity Provider:

```
        - name: google
          type: OIDCIdentityProvider
          mappingMethod: auto
          provider:
            issuer: https://accounts.google.com
            scopes:
            - openid
            - email
            - profile
            clientID: '********.apps.googleusercontent.com'
            idTokenSkipVerify: true
            clientSecret: '******'
            redirectURL: 'https://***.***.***/oauth/redirect/google'
```

I can't sign in with my Google Account.

![image](https://user-images.githubusercontent.com/8263040/109471531-d8c94f00-7aab-11eb-95fa-21a3a0699ada.png)
