### ISSUE TITLE
Failed to start etcd cluster

### ISSUE THREAD

**Issue by minicloudsky** [kubesphere/kubesphere#3435]
**Describe the Bug**
Failed to start etcd cluster: Failed to exec 

**Versions Used**
KubeSphere: v3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this) v1.17.9

**Environment**
How many nodes and their hardware configuration:
three nodes,both are centos7,with 2 cpu and 4 G RAM
tencentcloud(master)
huaweicloud2(worker)
aliyun(worker)
My yaml like below,due to my 3 server are in huaweicloud,aliyun,tencentcloud,so my  internalAddress are all the same as my address,both are public ip.
```yaml
apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: tencentcloud, address: xxx.xxx.xxx.xxx, internalAddress: xxx.xxx.xxx.xxx, user: root, password: xxx}
  - {name: huaweicloud2, address: xxx.xxx.xxx.xxx, internalAddress: xxx.xxx.xxx.xxx, user: root, password: xxx}
  - {name: aliyun, address: xxx.xxx.xxx.xxx, internalAddress: xxx.xxx.xxx.xxx, user: root, password: xxx}
  roleGroups:
    etcd:
    - tencentcloud
    master:
    - tencentcloud
    worker:
    - huaweicloud2
    - aliyun
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: "6443"
  kubernetes:
    version: v1.17.9
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []
---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.0.0
spec:
  local_registry: ""
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    es:
      elasticsearchDataVolumeSize: 20Gi
      elasticsearchMasterVolumeSize: 4Gi
      elkPrefix: logstash
      logMaxAge: 7
    mysqlVolumeSize: 20Gi
    minioVolumeSize: 20Gi
    etcdVolumeSize: 20Gi
    openldapVolumeSize: 2Gi
    redisVolumSize: 2Gi
  console:
    enableMultiLogin: false  # enable/disable multi login
    port: 30880
  alerting:
    enabled: false
  auditing:
    enabled: false
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    ruler:
      enabled: true
      replicas: 2
  logging:
    enabled: false
    logsidecarReplicas: 2
  metrics_server:
    enabled: true
  monitoring:
    prometheusMemoryRequest: 400Mi
    prometheusVolumeSize: 20Gi
  multicluster:
    clusterRole: none  # host | member | none
  networkpolicy:
    enabled: false
  notification:
    enabled: false
  openpitrix:
    enabled: false
  servicemesh:
    enabled: false

```

**How To Reproduce**
./kk create cluster -f config-sample.yaml

**Expected behavior**
expect everything are work fire,and the cluster can deployed successfully~
**The full stack trace**

```shell
[root@tencentcloud ~]# ./kk create cluster -f config-sample.yaml
+--------------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| name         | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker | nfs client | ceph client | glusterfs client | time         |
+--------------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| tencentcloud | y    | y    | y       | y        |       | y     |           | y      |            |             |                  | CST 15:34:53 |
| huaweicloud2 | y    | y    | y       | y        |       | y     |           | y      |            |             |                  | CST 15:34:55 |
| aliyun       | y    | y    | y       | y        | y     | y     | y         | y      | y          |             |                  | CST 15:34:59 |
+--------------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, you should ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: yes
INFO[15:35:06 CST] Downloading Installation Files               
INFO[15:35:06 CST] Downloading kubeadm ...                      
INFO[15:35:06 CST] Downloading kubelet ...                      
INFO[15:35:06 CST] Downloading kubectl ...                      
INFO[15:35:07 CST] Downloading helm ...                         
INFO[15:35:07 CST] Downloading kubecni ...                      
INFO[15:35:07 CST] Configurating operating system ...           
[tencentcloud 49.234.215.229] MSG:
net.ipv4.ip_forward = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
net.ipv4.conf.all.promote_secondaries = 1
net.ipv4.conf.default.promote_secondaries = 1
net.ipv6.neigh.default.gc_thresh3 = 4096
net.ipv4.neigh.default.gc_thresh3 = 4096
kernel.softlockup_panic = 1
kernel.sysrq = 1
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
kernel.numa_balancing = 0
kernel.shmmax = 68719476736
kernel.printk = 5
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
[huaweicloud2 121.36.77.126] MSG:
vm.swappiness = 0
net.core.somaxconn = 1024
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
[aliyun 39.105.154.2] MSG:
vm.swappiness = 0
kernel.sysrq = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
fs.inotify.max_user_watches = 524288
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
INFO[15:35:19 CST] Installing docker ...                        
INFO[15:35:21 CST] Start to download images on all nodes        
[aliyun] Downloading image: kubesphere/pause:3.1
[tencentcloud] Downloading image: kubesphere/etcd:v3.3.12
[huaweicloud2] Downloading image: kubesphere/pause:3.1
[huaweicloud2] Downloading image: kubesphere/kube-proxy:v1.17.9
[tencentcloud] Downloading image: kubesphere/pause:3.1
[huaweicloud2] Downloading image: coredns/coredns:1.6.9
[huaweicloud2] Downloading image: kubesphere/k8s-dns-node-cache:1.15.12
[tencentcloud] Downloading image: kubesphere/kube-apiserver:v1.17.9
[huaweicloud2] Downloading image: calico/kube-controllers:v3.15.1
[aliyun] Downloading image: kubesphere/kube-proxy:v1.17.9
[tencentcloud] Downloading image: kubesphere/kube-controller-manager:v1.17.9
[aliyun] Downloading image: coredns/coredns:1.6.9
[huaweicloud2] Downloading image: calico/cni:v3.15.1
[tencentcloud] Downloading image: kubesphere/kube-scheduler:v1.17.9
[huaweicloud2] Downloading image: calico/node:v3.15.1
[huaweicloud2] Downloading image: calico/pod2daemon-flexvol:v3.15.1
[tencentcloud] Downloading image: kubesphere/kube-proxy:v1.17.9
[aliyun] Downloading image: kubesphere/k8s-dns-node-cache:1.15.12
[tencentcloud] Downloading image: coredns/coredns:1.6.9
[tencentcloud] Downloading image: kubesphere/k8s-dns-node-cache:1.15.12
[aliyun] Downloading image: calico/kube-controllers:v3.15.1
[tencentcloud] Downloading image: calico/kube-controllers:v3.15.1
[aliyun] Downloading image: calico/cni:v3.15.1
[tencentcloud] Downloading image: calico/cni:v3.15.1
[tencentcloud] Downloading image: calico/node:v3.15.1
[aliyun] Downloading image: calico/node:v3.15.1
[tencentcloud] Downloading image: calico/pod2daemon-flexvol:v3.15.1
[aliyun] Downloading image: calico/pod2daemon-flexvol:v3.15.1
INFO[15:37:03 CST] Generating etcd certs                        
INFO[15:37:03 CST] Synchronizing etcd certs                     
INFO[15:37:04 CST] Creating etcd service                        
INFO[15:37:05 CST] Starting etcd cluster                        
[tencentcloud 49.234.215.229] MSG:
Configuration file will be created
INFO[15:37:05 CST] Refreshing etcd configuration                
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
ERRO[15:38:41 CST] Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://49.234.215.229:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 49.234.215.229:2379: connect: connection refused

error #0: dial tcp 49.234.215.229:2379: connect: connection refused: Process exited with status 1  node=49.234.215.229
WARN[15:38:41 CST] Task failed ...                              
WARN[15:38:41 CST] error: interrupted by error                  
Error: Failed to refresh etcd configuration: interrupted by error
Usage:
  kk create cluster [flags]

Flags:
  -f, --filename string          Path to a configuration file
  -h, --help                     help for cluster
      --skip-pull-images         Skip pre pull images
      --with-kubernetes string   Specify a supported version of kubernetes
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.0.0)
  -y, --yes                      Skip pre-check of the installation

Global Flags:
      --debug   Print detailed information (default true)

Failed to refresh etcd configuration: interrupted by error
```

**Comment by FeynmanZhou** [comment]
The servers of your cluster are provided by different cloud providers? It is not the best practice for provisioning a cluster and it's not recommended by the community.

**Comment by minicloudsky** [comment]
> The servers of your cluster are provided by different cloud providers? It is not the best practice for provisioning a cluster and it's not recommended by the community.

yes,But i can not figure out the problem of why etcd can not start, ssh connect between the three are ok

**Comment by minicloudsky** [comment]
It seems that etcd does not installed,the full stack trace
```shell
WARN[09:42:55 CST] Task failed ...                              
WARN[09:42:55 CST] error: Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://49.234.215.229:2379 cluster-health | grep -q 'cluster is healthy'" 
: Process exited with status 1 
Error: Failed to start etcd cluster: Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://49.234.215.229:2379 cluster-health | grep -q 'cluster is healthy'" 
: Process exited with status 1
Usage:
  kk add nodes [flags]

Flags:
  -f, --filename string    Path to a configuration file
  -h, --help               help for nodes
      --skip-pull-images   Skip pre pull images
  -y, --yes                Skip pre-check of the installation

Global Flags:
      --debug   Print detailed information (default true)

Failed to start etcd cluster: Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://49.234.215.229:2379 cluster-health | grep -q 'cluster is healthy'" 
: Process exited with status 1
```

in worker node(huaweicloud2),I tried to exec the above command
```shell
[root@huaweicloud2 ~]# sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-tencentcloud-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://49.234.215.229:2379 cluster-health | grep -q 'cluster is healthy'"
/bin/sh: /usr/local/bin/etcdctl: No such file or directory
[root@huaweicloud2 ~]# which etcd
/usr/bin/which: no etcd in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
[root@huaweicloud2 ~]# find / -name etcd
[root@huaweicloud2 ~]# 

```
Is there a way to configure etcd manually? thank you very much ~

**Comment by RolandMa1986** [comment]
Hi @minicloudsky ,
1. Please check your firewall settings, make sure port 2345  is opened.
2. According to your EIP type, You need to check whether a  port map is needed.
3. Login to your master and user `systemctl status etcd` or netstat to check if the etcd was started successfully

**Comment by minicloudsky** [comment]
I reinstalled my operating systems,and opened all my server ports in security group and shutdown the firewall, and ssh connection with each other is ok,however,it seems  that the problem is about network connection,any suggestions whill be appreciate to me,thanks~
my stack trace
```shell
INFO[14:16:23 CST] Refreshing etcd configuration                
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
ERRO[14:18:01 CST] Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-node1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-node1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://121.36.77.126:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 121.36.77.126:2379: connect: connection refused

error #0: dial tcp 121.36.77.126:2379: connect: connection refused: Process exited with status 1  node=121.36.77.126
WARN[14:18:01 CST] Task failed ...                              
WARN[14:18:01 CST] error: interrupted by error                  
Error: Failed to refresh etcd configuration: interrupted by error
Usage:
  kk create cluster [flags]

Flags:
  -f, --filename string          Path to a configuration file
  -h, --help                     help for cluster
      --skip-pull-images         Skip pre pull images
      --with-kubernetes string   Specify a supported version of kubernetes
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.0.0)
  -y, --yes                      Skip pre-check of the installation

Global Flags:
      --debug   Print detailed information (default true)

Failed to refresh etcd configuration: interrupted by error
[root@master ~]# 
```
![image](https://user-images.githubusercontent.com/32286819/110432742-7810c680-80ea-11eb-936e-d60d2d9ff7ec.png)
![image](https://user-images.githubusercontent.com/32286819/110432769-85c64c00-80ea-11eb-9644-7d77b5516f35.png)
can you help me figure out the problem,thaank you very much ~

**Comment by minicloudsky** [comment]
on node1,etcd seems have some problems.
![image](https://user-images.githubusercontent.com/32286819/110433340-477d5c80-80eb-11eb-8a0e-115a94f847ee.png)

**Comment by minicloudsky** [comment]
on master,telnet connect to node1 was refused
![image](https://user-images.githubusercontent.com/32286819/110434747-274e9d00-80ed-11eb-9067-0fd2a5a69457.png)
firewalld all closed
![image](https://user-images.githubusercontent.com/32286819/110435018-7694cd80-80ed-11eb-87e3-3e0e5f56c6e3.png)

![image](https://user-images.githubusercontent.com/32286819/110434958-654bc100-80ed-11eb-8a65-0fac1b626521.png)

**Comment by RolandMa1986** [comment]
@minicloudsky  I don't think it's possible setup the K8S cluster just using the public IP. You can't fill the public IP as same as your Internal IP. The Internal IP must be one of your Ethernet interfaces.

**Comment by minicloudsky** [comment]
> @minicloudsky I don't think it's possible setup the K8S cluster just using the public IP. You can't fill the public IP as same as your Internal IP. The Internal IP must be one of your Ethernet interfaces.

thank you very much ,I will add the internal Ip and retry.

**Comment by RolandMa1986** [comment]
> > @minicloudsky I don't think it's possible setup the K8S cluster just using the public IP. You can't fill the public IP as same as your Internal IP. The Internal IP must be one of your Ethernet interfaces.
> 
> thank you very much ,I will add the internal Ip and retry.

But another issue is you can't connnet each other Node by using their private IP. You must setup a tunnel between the Nodes.

**Comment by minicloudsky** [comment]
I deleted the cluster and added the master and node1 with The Internal IP,however,the etcd still seems does not start.what is the problem 
```shell
[root@master ~]# ./kk delete cluster -f config-sample.yaml
Are you sure to delete this cluster? [yes/no]: yes
INFO[15:48:21 CST] Resetting kubernetes cluster ...             
[master 49.234.215.229] MSG:
sudo -E /bin/sh -c "iptables -F && iptables -X && iptables -F -t nat && iptables -X -t nat && ip link del kube-ipvs0 && ip link del nodelocaldns"
[node1 121.36.77.126] MSG:
sudo -E /bin/sh -c "iptables -F && iptables -X && iptables -F -t nat && iptables -X -t nat && ip link del kube-ipvs0 && ip link del nodelocaldns"
INFO[15:48:24 CST] Successful.                                  
[root@master ~]# ./kk create cluster -f config-sample.yaml

+--------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| name   | sudo | curl | openssl | ebtables | socat | ipset | conntrack | docker | nfs client | ceph client | glusterfs client | time         |
+--------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+
| master | y    | y    | y       | y        |       | y     |           | y      |            |             |                  | CST 15:50:03 |
| node1  | y    | y    | y       | y        |       | y     |           | y      |            |             |                  | CST 15:50:04 |
+--------+------+------+---------+----------+-------+-------+-----------+--------+------------+-------------+------------------+--------------+

This is a simple check of your environment.
Before installation, you should ensure that your machines meet all requirements specified at
https://github.com/kubesphere/kubekey#requirements-and-recommendations

Continue this installation? [yes/no]: Continue this installation? [yes/no]: yes
INFO[15:50:06 CST] Downloading Installation Files               
INFO[15:50:06 CST] Downloading kubeadm ...                      
INFO[15:50:06 CST] Downloading kubelet ...                      
INFO[15:50:06 CST] Downloading kubectl ...                      
INFO[15:50:07 CST] Downloading helm ...                         
INFO[15:50:07 CST] Downloading kubecni ...                      
INFO[15:50:07 CST] Configurating operating system ...           
[master 49.234.215.229] MSG:
net.ipv4.ip_forward = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.default.accept_source_route = 0
kernel.core_uses_pid = 1
net.ipv4.tcp_syncookies = 1
kernel.msgmnb = 65536
kernel.msgmax = 65536
net.ipv4.conf.all.promote_secondaries = 1
net.ipv4.conf.default.promote_secondaries = 1
net.ipv6.neigh.default.gc_thresh3 = 4096
net.ipv4.neigh.default.gc_thresh3 = 4096
kernel.softlockup_panic = 1
kernel.sysrq = 1
net.ipv6.conf.all.disable_ipv6 = 0
net.ipv6.conf.default.disable_ipv6 = 0
net.ipv6.conf.lo.disable_ipv6 = 0
kernel.numa_balancing = 0
kernel.shmmax = 68719476736
kernel.printk = 5
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
[node1 121.36.77.126] MSG:
vm.swappiness = 0
net.core.somaxconn = 1024
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.ip_forward = 1
net.bridge.bridge-nf-call-arptables = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
net.ipv4.ip_local_reserved_ports = 30000-32767
INFO[15:50:11 CST] Installing docker ...                        
INFO[15:50:12 CST] Start to download images on all nodes        
[node1] Downloading image: kubesphere/etcd:v3.3.12
[master] Downloading image: kubesphere/pause:3.1
[node1] Downloading image: kubesphere/pause:3.1
[master] Downloading image: kubesphere/kube-apiserver:v1.17.9
[node1] Downloading image: kubesphere/kube-proxy:v1.17.9
[node1] Downloading image: coredns/coredns:1.6.9
[master] Downloading image: kubesphere/kube-controller-manager:v1.17.9
[node1] Downloading image: kubesphere/k8s-dns-node-cache:1.15.12
[node1] Downloading image: calico/kube-controllers:v3.15.1
[master] Downloading image: kubesphere/kube-scheduler:v1.17.9
[node1] Downloading image: calico/cni:v3.15.1
[node1] Downloading image: calico/node:v3.15.1
[master] Downloading image: kubesphere/kube-proxy:v1.17.9
[node1] Downloading image: calico/pod2daemon-flexvol:v3.15.1
[master] Downloading image: coredns/coredns:1.6.9
[master] Downloading image: kubesphere/k8s-dns-node-cache:1.15.12
[master] Downloading image: calico/kube-controllers:v3.15.1
[master] Downloading image: calico/cni:v3.15.1
[master] Downloading image: calico/node:v3.15.1
[master] Downloading image: calico/pod2daemon-flexvol:v3.15.1
INFO[15:51:26 CST] Generating etcd certs                        
INFO[15:51:29 CST] Synchronizing etcd certs                     
INFO[15:51:29 CST] Creating etcd service                        
INFO[15:51:32 CST] Starting etcd cluster                        
[node1 121.36.77.126] MSG:
Configuration file will be created
INFO[15:51:33 CST] Refreshing etcd configuration                
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
Waiting for etcd to start
ERRO[15:53:11 CST] Failed to start etcd cluster: Failed to exec command: sudo -E /bin/sh -c "export ETCDCTL_API=2;export ETCDCTL_CERT_FILE='/etc/ssl/etcd/ssl/admin-node1.pem';export ETCDCTL_KEY_FILE='/etc/ssl/etcd/ssl/admin-node1-key.pem';export ETCDCTL_CA_FILE='/etc/ssl/etcd/ssl/ca.pem';/usr/local/bin/etcdctl --endpoints=https://192.168.0.128:2379 cluster-health | grep -q 'cluster is healthy'" 
Error:  client: etcd cluster is unavailable or misconfigured; error #0: dial tcp 192.168.0.128:2379: connect: connection refused

error #0: dial tcp 192.168.0.128:2379: connect: connection refused: Process exited with status 1  node=121.36.77.126
WARN[15:53:11 CST] Task failed ...                              
WARN[15:53:11 CST] error: interrupted by error                  
Error: Failed to refresh etcd configuration: interrupted by error
Usage:
  kk create cluster [flags]

Flags:
  -f, --filename string          Path to a configuration file
  -h, --help                     help for cluster
      --skip-pull-images         Skip pre pull images
      --with-kubernetes string   Specify a supported version of kubernetes
      --with-kubesphere          Deploy a specific version of kubesphere (default v3.0.0)
  -y, --yes                      Skip pre-check of the installation

Global Flags:
      --debug   Print detailed information (default true)

Failed to refresh etcd configuration: interrupted by error
```
my config like below
```yaml

apiVersion: kubekey.kubesphere.io/v1alpha1
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: master, address: 49.234.215.229, internalAddress: 172.17.0.17, user: root, password: Jyw83139200..}
  - {name: node1, address: 121.36.77.126, internalAddress: 192.168.0.128, user: root, password: Jyw83139200..}
  roleGroups:
    etcd:
    - node1
    master:
    - master
    worker:
    - node1
  controlPlaneEndpoint:
    domain: lb.kubesphere.local
    address: ""
    port: "6443"
 kubernetes:
    version: v1.17.9
    imageRepo: kubesphere
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
  registry:
    registryMirrors: []
    insecureRegistries: []
  addons: []
```
