### ISSUE TITLE
Failed to login with LDAP account

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/kubesphere#3506]
**Describe the Bug**
1. Setup LDAP server and test account
2. Edit cc using `kubectl -n kubesphere-system edit cc ks-installer` as below:
```yaml
        identityProviders:
        - name: ldap
          mappingMethod: 'auto'
          type: 'LDAPIdentityProvider'
          provider:
            host: 'xxx'
            loginAttribute: 'uid'
            mailAttribute: 'mail'
            managerDN: 'xxx'
            managerPassword: 'xxx'
            userSearchBase: 'xxx'
```
3. Wait for the config to complete by `kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f`
4. Login ks console with LDAP test account failed

**Versions Used**
KubeSphere: v3.1.0-nightly-20210316
Kubernetes: (If KubeSphere installer used, you can skip this)
