### ISSUE TITLE
OIDC doesn't compiable with Azure Active Directory

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#3512]
**Describe the Bug**
There;s an error happend when confirm user's name 
**Versions Used**
KubeSphere: nightly-20210318

**How To Reproduce**
1. Enable Azure Active Directory Service and register an application as kubesphere.
2. Config OIDC authentication as below
```yaml
    - name: microsoft
      type: OIDCIdentityProvider
      mappingMethod: auto
      provider:
        issuer: https://login.microsoftonline.com/<your  tenant id>
        clientID: 'xxx-xxx'
        clientSecret: 'xxx-xxx'
        redirectURL: 'http://localhost:30880/oauth/redirect/microsoft'
        idTokenSkipVerify: true
        scopes:
        - openid
        - email
```
3. Click `microsoft` on the login page and Login with a Microsoft account.
4. Change the user name on the confirm login page and click `Login`. An error was shown on the page
![azure](https://user-images.githubusercontent.com/1720333/111563217-80e05700-87d2-11eb-8a10-1df7905411c0.png)

**Expected behavior**
A new User account can be register and login successfully.

/kind bug 
/priority low
/area security
