### ISSUE TITLE
Failed to update custom monitoring via editing config file

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/kubesphere#3616]
**Describe the Bug**
The refresh interview is still none on the template view after the update via the config file editing mode.

Below is the config file:
```
apiVersion: monitoring.kubesphere.io/v1alpha1
kind: ClusterDashboard
metadata:
  annotations:
    kubesphere.io/creator: admin
  name: '111'
spec:
  panels: []
  refresh: 5s
  templatings: []
  time:
    from: now-30m
    to: now
  title: ''
```

Below is the screenshot of the custom monitoring template page.

![image](https://user-images.githubusercontent.com/1450685/112791803-d64f1a80-9094-11eb-9c3e-01483e380f9a.png)

/area observability 
/priority high

**Versions Used**
KubeSphere: `nightly-20210328`

**Environment**
This is not an environmental issue.

**How To Reproduce**
1. Go to the Custom monitoring page
2. Create a custom monitoring item
3. Edit the custom monitoring item via config file editing mode. Update the refresh interview to `5s`
4. Check the custom monitoring item via template view

**Expected behavior**
Users can see the same value no matter from config file mode or template view mode.
