### ISSUE TITLE
Got a negative cost on the billing page

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/kubesphere#3747]
**Describe the Bug**

Got a negative cost on the billing page. You can see it from the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/114961026-cf991380-9e9a-11eb-9ea2-0af102f58702.png)

/priority medium

**Versions Used**
KubeSphere: `20210414`

**Environment**
This should not be an environmental issue.

**How To Reproduce**
1.  Change the ConfigMap `ks-metering-config`
2. Restart `ks-apiserver`
3. Check the Metering and Billing page

An example of the ConfigMap:
```
apiVersion: v1
data:
  ks-metering.yaml: |
    retentionDay: 7d
    billing:
      priceInfo:
        currencyUnit: "AB"
        cpuPerCorePerHour: 2
        memPerGigabytesPerHour: -1
        ingressNetworkTrafficPerGiagabytesPerHour: -1
        egressNetworkTrafficPerGigabytesPerHour: -1
        pvcPerGigabytesPerHour: -1
kind: ConfigMap
```

**Expected behavior**
Don't use the invalid price.
