### ISSUE TITLE
[priority high]After creating a long user name in KubeSphere 3.0, deleting the user will cause the system to crash.

### ISSUE THREAD

**Issue by peiyaos** [kubesphere/kubesphere#3784]
**Describe the Bug**
KubeSphere 3.0 installed with ks-installer,after creating a long user name in KubeSphere 3.0, deleting the user will cause the system to crash.

**How To Reproduce**
1.For example, the user name as shown below.
![image](https://user-images.githubusercontent.com/48174496/115518912-47ac7280-a2bb-11eb-9421-7d23a671d236.png)
2.Delete the user in the image above.
3.When accessing the system again, the browser reported the following status, which made it unavailable.
![image](https://user-images.githubusercontent.com/48174496/115522059-5b0d0d00-a2be-11eb-8ff5-ac4a45640b83.png)

**Versions Used**
KubeSphere: 3.0（It is expected that 3.1 will also have this problem.）
Kubernetes: 1.18.8

**Expected behavior**
1.Add verification when creating users, and prohibit creating users with long user names

/kind bug
/priority high

**Comment by peiyaos** [comment]
By viewing the ks-apiserver log, the error is reported as follows.
![image](https://user-images.githubusercontent.com/48174496/115522740-f605e700-a2be-11eb-8fbe-91bedb44c452.png)
Check the user list and find that users with abnormal names still exist.
![image](https://user-images.githubusercontent.com/48174496/115523686-e8049600-a2bf-11eb-81c8-1240b89b7d60.png)
However, globalrolebindings no longer exists. Initially, it is suspected that the user name is too long, and the specified user is not queried when deleting.
![image](https://user-images.githubusercontent.com/48174496/115524359-a2949880-a2c0-11eb-8bf1-bb35166903c2.png)

**Comment by wansir** [comment]
> By viewing the ks-apiserver log, the error is reported as follows.
> ![image](https://user-images.githubusercontent.com/48174496/115522740-f605e700-a2be-11eb-8fbe-91bedb44c452.png)
> Check the user list and find that users with abnormal names still exist.
> ![image](https://user-images.githubusercontent.com/48174496/115523686-e8049600-a2bf-11eb-81c8-1240b89b7d60.png)
> However, globalrolebindings no longer exists. Initially, it is suspected that the user name is too long, and the specified user is not queried when deleting.
> ![image](https://user-images.githubusercontent.com/48174496/115524359-a2949880-a2c0-11eb-8bf1-bb35166903c2.png)

It seems that clusterrolebinding was accidentally deleted.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubesphere
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubesphere
  namespace: kubesphere-system
```
