### ISSUE TITLE
Failed to create Credentials in DevOps Projects

### ISSUE THREAD

**Issue by daniel-hutao** [kubesphere/kubesphere#3800]
**Describe the Bug**

I Got Sync Failed error when create a credential named harbor-id

![image](https://user-images.githubusercontent.com/18692628/115977832-13340180-a5ae-11eb-961a-6ea59d10e32d.png)

**Versions Used**
KubeSphere: nightly-20210422
Kubernetes: v1.18.14

** More Logs**

- ks-apiserver

![image](https://user-images.githubusercontent.com/18692628/115977898-9f462900-a5ae-11eb-801c-b38678fe7148.png)

- ks-controller-manager

![image](https://user-images.githubusercontent.com/18692628/115977904-a8cf9100-a5ae-11eb-85a5-cbd0feb085a3.png)

/kind bug
/area devops

**Comment by JohnNiang** [comment]
Can you login in Jenkins Dashboard by admin account?

**Comment by daniel-hutao** [comment]
> Can you login in Jenkins Dashboard by admin account?

![image](https://user-images.githubusercontent.com/18692628/115978432-f0a3e780-a5b1-11eb-8c91-744afb910244.png)

Yeah

**Comment by wansir** [comment]
@daniel-hutao Please check the logs of ks-installer.

`kubectl -n kubesphere-system get cm kubesphere-config`

```
    authentication:
      jwtSecret: "{{ ks_secret_str.stdout }}"
    devops:
      host: http://ks-jenkins.kubesphere-devops-system.svc/
      username: admin
      password: {{ ks_token_str.stdout }}
```

Password in the DevOps section is a user token (auto-generated) that needs to match `jwtSecret`.

You can check if the token is valid through [jwt.io](https://jwt.io). 

See also
https://github.com/kubesphere/ks-installer/blob/master/roles/ks-core/config/templates/kubesphere-config.yaml.j2#L75
https://github.com/kubesphere/ks-installer/blob/f40fc46fc911ecd271a3510faade0d61b706204e/roles/ks-core/init-token/tasks/main.yaml#L51-L70
