### ISSUE TITLE
Failed to login with GitHub account

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#3850]
**Describe the Bug**

Failed to login with GitHub account, after upgrading from 3.0 to 3.1.

```
{
  code: 403,
  kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message: 'users.iam.kubesphere.io is forbidden: User "system:pre-registration" cannot create resource "users" in API group "iam.kubesphere.io" at the cluster scope',
  reason: 'Forbidden',
  details: { group: 'iam.kubesphere.io', kind: 'users' },
  statusText: 'Forbidden'
}
```

**Versions Used**
KubeSphere: v3.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by wansir** [comment]
Workaround

```
cat << EOF | kubectl apply -f -
apiVersion: iam.kubesphere.io/v1alpha2
kind: GlobalRoleBinding
metadata:
  name: pre-registration
roleRef:
  apiGroup: iam.kubesphere.io
  kind: GlobalRole
  name: pre-registration
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: pre-registration
EOF
```
