### ISSUE TITLE
openpitrix installs app failed when helm chart contains duplicate keys.

### ISSUE THREAD

**Issue by xyz-li** [kubesphere/kubesphere#3933]
**Describe the Bug**
openpitrix failed to install app when chart contains duplicate keys.
 Because openpitrix needs add extra annotations and labels to helm release with kustomize which will return errors when manifest contains duplicate keys.

![image](https://user-images.githubusercontent.com/6263928/120583455-d850a380-c460-11eb-8e8b-db38dc5d63ba.png)

**Versions Used**
KubeSphere: v3.1.0
kustomize: v4.1.0

**How To Reproduce**
1. Click on 'Deploy New App'
2. Click on 'From App Store'
3. Choose then app 'Memcached'
4. Edit `App Configurations` , change ```affinity: {}``` to 
```
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/os
          operator: In
          values:
          - linux
```
5.  At last, deploy the app

related issues: 
https://github.com/kubernetes-sigs/kustomize/issues/3480
