### ISSUE TITLE
Service Monitor is not deleted  after the service is deleted

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#3992]
**Describe the Bug**
1.After creating the service, go to the service details page
2.Create the Service Monitor for the service
3.then delete the service and associated workload
4.Go to the CRD page of the Service Monitor
5.The Service Monitor for the above service has not been deleted

![image](https://user-images.githubusercontent.com/36271543/123196218-1c711a00-d4dc-11eb-9bb1-6da8e159081a.png)
![image](https://user-images.githubusercontent.com/36271543/123196311-462a4100-d4dc-11eb-9226-aa049470d164.png)

**Versions Used**
KubeSphere: ks v3.1.1

/kind bug
/assign @benjaminhuo 
/priority medium
/milestone v3.1

**Comment by junotx** [comment]
Currently the servicemonitor was not bound to the service, so it would not be deleted after the service was deleted

**Comment by junotx** [comment]
@harrisonliu5 when ask the backend to create a servicemonitor from this service page, add this service info to its `ownerReferences`. Here is an example: 
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: details
  namespace: test
  ownerReferences: 
  - apiVersion: v1
    kind: Service
    name: <service-name>
    uid: <service-uid>
spec:
...
```
/assign @harrisonliu5
