### ISSUE TITLE
[proposal] GPUKind config

### ISSUE THREAD

**Issue by lxm** [kubesphere/kubesphere#4025]
According to GPU workload scheduling requirements and there exist multi GPU scheduling tech.
We need a definition for cluster's GPU resource.

My idea is as follows:

add CRD GPUKind

``` 
name: nvidia
spec:
    - key: "nvidia.com/gpu"
        alias: "GPU"
        valtype: integer

```

``` 
name: tke-gpu-manager
spec:
    - key: "tencent.com/vcuda-core"
        alias: "GPU"
        valtype: float
    - key: "tencent.com/vcuda-memory"
        alias: "MEM"
        valtype: integer

```

```
name: aliyun-gpu-share
spec:
    - key: "aliyun.com/gpu-mem"
        alias: "MEM"
        valtype: integer
```
