### ISSUE TITLE
Support setting host cluster name 

### ISSUE THREAD

**Issue by swiftslee** [kubesphere/kubesphere#4158]
Currently, the host cluster name is hard-coded to `host`. 
![image](https://user-images.githubusercontent.com/37265389/130204038-94badce0-81eb-47b6-a4ed-1ae4842bf02a.png)

We need to specify the host cluster name in the `cc` config and convert it into `ks-console-config` configmap.

**Comment by yuswift** [comment]
Here is the configMap of ks-console-config and the ks-installer config. What about adding a `hostClusterName` field? @zryfish 
```
server:
  http:
    hostname: localhost
    port: 8000
    static:
      production:
        /public: server/public
        /assets: dist/assets
        /dist: dist
  redis:
    port: 6379
    host: redis.kubesphere-system.svc
  redisTimeout: 5000
  sessionTimeout: 7200000
client:
  version:
    kubesphere: v3.1.1
    kubernetes: v1.19.8
    openpitrix: v0.3.5
  enableKubeConfig: true
hostClusterName: host
```


ks-installer config
```
  multicluster:
    clusterRole: none  # host | member | none  # You can install a solo cluster, or specify it as the Host or Member Cluster.
    hostClusterName: host
```
