### ISSUE TITLE
Unable view all application's Services and Workloads after upgrade kubesphere from v3.0.0 to v3.1.1

### ISSUE THREAD

**Issue by kerwinan** [kubesphere/kubesphere#4270]
**Conditions**
- one host cluster(aliyun ACK, 2 nodes, kubesphere v3.0.0)
- one member cluster(aliyun ACK, 11 nodes, kubesphere v3.0.0)

**Describe the Bug**
Upgrade host kubesphere from v3.0.0 to v3.1.1. Then view a application's status of host cluster or member cluster, unable view it's Services and Workloads.

![Screenshot from 2021-09-23 18-20-35](https://user-images.githubusercontent.com/30976902/134491402-5b7cc2fe-8236-4165-bd66-bf0d1dc3ff28.png)

**How To Reproduce**

1. enter kubesphere **host cluster**' web console
2. [kubectl apply -f https://github.com/kubesphere/ks-installer/releases/download/v3.1.1/kubesphere-installer.yaml](https://kubesphere.com.cn/docs/upgrade/upgrade-with-ks-installer/)
3. then, kubesphere **host cluster(v3.1.1)**, kubesphere **member cluster(v3.0.0)**

**Expected behavior**
The kubesphere host cluster is successfully upgraded to v3.1.1, and enable view all application's Services and Workloads before the upgrade

By analyzing the ks-api request, it is found that the **deployment.yaml** and **services.yaml** files corresponding to the application lack a "**app.kubesphere.io/instance**" label.
```yaml
{
  "metadata": {
    "name": "xxx",
    "namespace": "xxx",
    "selfLink": "/api/v1/namespaces/{namespace}/services/xxx",
    "uid": "xxx",
    "resourceVersion": "253502458",
    "creationTimestamp": "2021-09-23T07:36:15Z",
    "labels": {
      "app.kubernetes.io/instance": "xxxx",
      "app.kubernetes.io/managed-by": "Helm",
      "app.kubernetes.io/name": "xxxx",
      "app.kubernetes.io/version": "0.0.5",
      "helm.sh/chart": "xxx-0.0.5_001"
    }
  }
}
```
kubesphere(v3.1.1)'s request url is: 
- http://{ip}/api/clusters/{cluster}/v1/namespaces/{namespace}/services?labelSelector=**app.kubesphere.io/instance**=xxx
- http://{ip}/apis/clusters/{cluster}/apps/v1/namespaces/{namespace}/deployments?labelSelector=**app.kubesphere.io/instance**=xxx

**So, it cannot view services and workloads that is because 'app.kubernetes.io/instance'.**

Then, I try to fix it, add a label(**app.kubernetes.io/instance**):
- kubectl get deployments.apps -n {namespace}
- kubectl edit deployments.apps {deployment_name} -n {namespace}
- kubectl get service -n {namespace}
- kubectl edit service {service_name} -n {namespace}

Through the above steps, the service and workload can be displayed normally.
![Screenshot from 2021-09-24 10-43-24](https://user-images.githubusercontent.com/30976902/134611293-966f262d-aa40-44ca-a058-37381dcb21f7.png)

Finally, I want to know if this is a bug.
