### ISSUE TITLE
After use ks-installer, the ks-console's LoadBalancer turn to NodePort.

### ISSUE THREAD

**Issue by elizabethvik** [kubesphere/kubesphere#4423]
**Describe the Bug**
After I used ks-installer install logging system , my ks-console's LoadBalancer became a NodePort, 
**Versions Used**
KubeSphere:3.2.0
Kubernetes: 1.21

**Environment**
EKS, Amazon Linux 2, 1node, 2CPU/4G

**How To Reproduce**
use ks-installer to enable logging.

**Comment by RolandMa1986** [comment]
/kind support 
@elizabethvik  please change the console service in your clusterconfiguration

```
  common:
    core:
      console:
        enableMultiLogin: true  # Enable or disable simultaneous logins. It allows different users to log in with the same account at the same time.
        port: 30880
        type: LoadBalancer 
```
