### ISSUE TITLE
Failed to login with LDAP after upgraded to v3.2.0

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/kubesphere#4435]
**Describe the Bug**
After upgrading to kubesphere v3.2.0, Failed to login with LDAP. Nothing shows when click on login button.

**Versions Used**
KubeSphere: V3.2.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
config a ldap provide like bellow:

```yaml
       identityProviders:
       - name: LDAP
         type: LDAPIdentityProvider
         mappingMethod: auto
         provider:
           host: 192.168.0.2:389
           managerDN: uid=root,cn=users,dc=nas
           managerPassword: ********
           userSearchBase: cn=users,dc=nas
           loginAttribute: uid
           mailAttribute: mail   
```

**How To Reproduce**

**Expected behavior**
Users can login with Ldap successfully

/kind bug 
/area iam
/priority high
