### ISSUE TITLE
service mesh bug

### ISSUE THREAD

**Issue by happywzy** [kubesphere/kubesphere#4490]
Version: V3.2.0
if my service have 2 port:
![image](https://user-images.githubusercontent.com/26290710/144019037-00c013da-271a-4354-a3d4-d917a5062569.png)

I created a grayscale distribution for this service. If the traffic is set to 50% each, the configuration of `VirtualService` :
```yaml
http:
    - match:
        - port: 17070
      route:
        - destination:
            host: grpc
            port:
              number: 17070
            subset: v1
          weight: 50
        - destination:
            host: grpc
            port:
              number: 17070
            subset: v2
          weight: 50
    - match:
        - port: 17072
      route:
        - destination:
            host: grpc
            port:
              number: 17072
            subset: v1
          weight: 50
        - destination:
            host: grpc
            port:
              number: 17072
            subset: v2
          weight: 50
```
But if I choose one version to take over all the traffic,Configuration becomes like this?? So the traffic on the other port doesn't take over.
```yaml
  http:
    - match:
        - port: 17070
      route:
        - destination:
            host: grpc
            port:
              number: 17070
            subset: v2
          weight: 100
```
