### ISSUE TITLE
Empty log on aws fargate nodes

### ISSUE THREAD

**Issue by yswtrue** [kubesphere/kubesphere#4499]
**Describe the Bug**

I have enabled logging, and normal nodes work well, but almost all pods on fargate nodes can't get logs. But sometimes It can record logs, sometimes not. Normal namespace logging is working fine.

**Versions Used**
KubeSphere: 3.2.0
Kubernetes: v1.22.4

**Environment**
How many nodes and their hardware configuration:

AWS Kubernetes cluster, with 6 x m6i.xlarge nodes, and some fargate nodes.

**How To Reproduce**
1. deploy AWS Kubernetes with eksctl
2. create fargate namespace
3. deploy something on fargate namespace
3. install kubesphere in normal namespace
4. enable logging

**Expected behavior**

These is some clusterconfig snippet
```
  logging:
    containerruntime: docker
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
    es:
      basicAuth:
        enabled: false
        password: ''
        username: ''
      data:
        volumeSize: 200Gi
      elkPrefix: logstash
      externalElasticsearchPort: ''
      externalElasticsearchUrl: ''
      generateID: true
      logMaxAge: 7
      master:
        volumeSize: 40Gi
```
