### ISSUE TITLE
Can't load custom prometheus rule

### ISSUE THREAD

**Issue by yswtrue** [kubesphere/kubesphere#4533]
I create a new PrometheusRule, but there is no new rule on prometheus rules. And I have to add groups into prometheus-k8s-rules

```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: matrix-rules
  namespace: matrix
spec:
  groups:
    - name: synapse
      rules:
        - expr: >-
            sum(synapse_federation_transaction_queue_pendingEdus or
            absent(synapse_federation_transaction_queue_pendingEdus)*0)
          record: 'synapse_federation_transaction_queue_pendingEdus:total'
        - expr: >-
            sum(synapse_federation_transaction_queue_pendingPdus or
            absent(synapse_federation_transaction_queue_pendingPdus)*0)
          record: 'synapse_federation_transaction_queue_pendingPdus:total'
        - expr: sum(synapse_http_server_request_count) by (method)
          labels:
            servlet: ''
          record: 'synapse_http_server_request_count:method'
        - expr: sum(synapse_http_server_request_count) by (servlet)
          labels:
            method: ''
          record: 'synapse_http_server_request_count:servlet'
        - expr: 'sum(synapse_http_server_request_count:by_method) by (servlet)'
          labels:
            servlet: ''
          record: 'synapse_http_server_request_count:total'
        - expr: >-
            rate(synapse_util_caches_cache:hits[5m]) /
            rate(synapse_util_caches_cache:total[5m])
          record: 'synapse_cache:hit_ratio_5m'
        - expr: >-
            rate(synapse_util_caches_cache:hits[30s]) /
            rate(synapse_util_caches_cache:total[30s])
          record: 'synapse_cache:hit_ratio_30s'
        - expr: synapse_federation_client_sent_edus + 0
          labels:
            type: EDU
          record: synapse_federation_client_sent
        - expr: 'synapse_federation_client_sent_pdu_destinations:count + 0'
          labels:
            type: PDU
          record: synapse_federation_client_sent
        - expr: sum(synapse_federation_client_sent_queries) by (job)
          labels:
            type: Query
          record: synapse_federation_client_sent
        - expr: synapse_federation_server_received_edus + 0
          labels:
            type: EDU
          record: synapse_federation_server_received
        - expr: synapse_federation_server_received_pdus + 0
          labels:
            type: PDU
          record: synapse_federation_server_received
        - expr: sum(synapse_federation_server_received_queries) by (job)
          labels:
            type: Query
          record: synapse_federation_server_received
        - expr: synapse_federation_transaction_queue_pending_edus + 0
          labels:
            type: EDU
          record: synapse_federation_transaction_queue_pending
        - expr: synapse_federation_transaction_queue_pending_pdus + 0
          labels:
            type: PDU
          record: synapse_federation_transaction_queue_pending
        - expr: >-
            sum without(type, origin_type, origin_entity)
            (synapse_storage_events_persisted_events_sep{origin_type="remote"})
          labels:
            type: remote
          record: synapse_storage_events_persisted_by_source_type
        - expr: >-
            sum without(type, origin_type, origin_entity)
            (synapse_storage_events_persisted_events_sep{origin_entity="*client*",origin_type="local"})
          labels:
            type: local
          record: synapse_storage_events_persisted_by_source_type
        - expr: >-
            sum without(type, origin_type, origin_entity)
            (synapse_storage_events_persisted_events_sep{origin_entity!="*client*",origin_type="local"})
          labels:
            type: bridges
          record: synapse_storage_events_persisted_by_source_type
        - expr: >-
            sum without(origin_entity, origin_type)
            (synapse_storage_events_persisted_events_sep)
          record: synapse_storage_events_persisted_by_event_type
        - expr: sum without(type) (synapse_storage_events_persisted_events_sep)
          record: synapse_storage_events_persisted_by_origin

```
