### ISSUE TITLE
 Optimize data retention policies for logging, auditing, and events

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/kubesphere#4604]
**What's it about?**

There are some issues with the current data retention policy for logging, auditing, and events.

1. The data retention period for logging, auditing, and events is the same and cannot be set individually.
2. Excessive cleaning when cleaning expired data. For example, when multiple clusters share an ES cluster, cluster a will also clear the expiration time of cluster b when it cleans up expired data. Problems can arise if clusters a and b have different data retention periods.

So, we need to optimize the data retention policies from the following aspects.

1. Support to set the separate data retention periods for logging, auditing, and events. We can add a parameter to `ClusterConfig` like this.

```
spec:
  common:
    es:
      logMaxAge: 7
  logging:
    logMaxAge: 15
  auditing:
    auditingMaxAge: 30
  events:
    eventMaxAge: 60
```

When `logging.logMaxAge` or `auditing.auditingMaxAge` or `evnets.eventMaxAge` is not set, `common.es.logMaxAge` will be used.

2. When cleaning expired data, the index needs to be filtered, and only the index created by the cluster can be deleted.
The config file for the curator may be like this.

```
1:
    action: delete_logging_indices
    description: "Clean up ES by deleting old indices"
    options:
      timeout_override:
      continue_if_exception: False
      disable_action: False
      ignore_empty_list: True
    filters:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 7
      field:
      stats_result:
      epoch:
      exclude: False
    - filtertype: pattern
      kind: prefix
      value: ks-logstash-log
      exclude: False  
```

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request
/area observability
