### ISSUE TITLE
When deleting a service, pods are not being related with resources

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4658]
**Describe the Bug**

When deleting a service, the pods associated with the service are not queried.
![image](https://user-images.githubusercontent.com/68640256/152937732-2fec3644-8edf-41e9-bf5a-35f15a209286.png)

![image](https://user-images.githubusercontent.com/68640256/152936389-7a790497-cbdf-4e3c-87a3-4e4a2d0cb59a.png)

**Versions Used**
KubeSphere:   `v3.2.1`

**How To Reproduce**
1. Create service and pod with yaml
 ```
apiVersion: v1
kind: Service
metadata:
  namespace: pro-h
  name: test-service
  labels:
    app: test-service
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
    nodePort: 30002
  selector:
    app: test-service
---
apiVersion: v1
kind: Pod
metadata:
  namespace: pro-h
  name: test-service
  labels:
    app: test-service
spec:
  containers:
  - name: test-service
    image: nginx:latest
    ports:
    - containerPort: 80
```
2. Delete service 'test-service'
3. the pods associated with the service are not queried

**Expected behavior**
When deleting a service, if there are no associated deployments\Statefulsets\Daemonsets, should query whether there are associated pods .

/priority medium
/assign @VioZhang
