### ISSUE TITLE
how to use istio configuration which not integration by kubesphere?

### ISSUE THREAD

**Issue by happywzy** [kubesphere/kubesphere#4700]
such as:
```yaml
$ kubectl apply -f - <<EOF
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
  - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: v2
    timeout: 0.5s
EOF
```
`timeout` is a configuration item provide by istio but not integration by kubesphere, how to use?
If I modify the resource `VirtualService` from the background, it will refresh by `ks` controller.
