### ISSUE TITLE
Traffic Monitoring Not Response

### ISSUE THREAD

**Issue by chj9** [kubesphere/kubesphere#4745]
![image](https://user-images.githubusercontent.com/16426260/160050234-0cd9a2b8-6e51-425f-ba98-57b80f21bbdc.png)
![image](https://user-images.githubusercontent.com/16426260/160050320-8dbc550c-6b84-4016-8e77-66443f51587e.png)
![image](https://user-images.githubusercontent.com/16426260/160050148-faf2ca51-393e-47a4-a19e-cfb71ed3191a.png)
## K8S Version
v1.22.3-aliyun.1

## kubesphere Version
v3.2.1

## Application
```
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: turnright-vip
  namespace: __APP_NAMESPACE__
  labels:
    app.kubernetes.io/version: __VERSION__
    app.kubernetes.io/name: vip
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/version: __VERSION__
      app.kubernetes.io/name: vip
  addOwnerRef: true
  componentKinds:
    - group: ''
      kind: Service
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: networking.k8s.io
      kind: Ingress
    - group: servicemesh.kubesphere.io
      kind: Strategy
    - group: servicemesh.kubesphere.io
      kind: ServicePolicy
```

## Deployment
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turnright-__CI_ENVIRONMENT_SLUG__
  namespace: __APP_NAMESPACE__
  labels:
    version: __VERSION__
    app: __CI_ENVIRONMENT_SLUG__
    app.kubernetes.io/version: __VERSION__
    app.kubernetes.io/name: vip
  annotations:
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      version: __VERSION__
      app: __CI_ENVIRONMENT_SLUG__
      app.kubernetes.io/version: __VERSION__
      app.kubernetes.io/name: vip
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        version: __VERSION__
        app: __CI_ENVIRONMENT_SLUG__
        app.kubernetes.io/version: __VERSION__
        app.kubernetes.io/name: vip
      annotations:
        gitlab-ci.last-updated-date: '__CI_LAST_UPDATE__'
        sidecar.istio.io/inject: 'true'
    spec:
    # serviceAccountName: atai-deploy
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - __CI_ENVIRONMENT_SLUG__
                topologyKey: "kubernetes.io/hostname"
      imagePullSecrets:
        - name: aliyun

      volumes:
        - name: app-config
          configMap:
            name: __CI_APP_CONFIG__
        - name: app-crt
          secret:
            secretName: app-crt

        - name: apm-config
          configMap:
            name: skywalking

        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''

        - name: skywalking-agent
          emptyDir: {}
      initContainers:
        - name: sw-agent-sidecar
          image: apache/skywalking-java-agent:__AGENT_VERSION__
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh","-c" ]
          args:
            - cp /skywalking/agent/optional-plugins/apm-trace-ignore-plugin-__AGENT_PLUGINS_VERSION__.jar /skywalking//agent/plugins/;
              cp /skywalking/agent/optional-plugins/apm-spring-tx-plugin-__AGENT_PLUGINS_VERSION__.jar /skywalking//agent/plugins/;
              cp /skywalking/agent/optional-plugins/apm-gson-2.x-plugin-__AGENT_PLUGINS_VERSION__.jar /skywalking//agent/plugins/;
              cp /skywalking/agent/optional-plugins/apm-guava-cache-plugin-__AGENT_PLUGINS_VERSION__.jar /skywalking/agent/plugins/;
              cp -R /skywalking/agent /agent/;

          volumeMounts:
            - name: skywalking-agent
              mountPath: /agent
      containers:
        - name: __CI_ENVIRONMENT_SLUG__
          image: __REGISTRY__:__VERSION__
          imagePullPolicy: Always
          volumeMounts:
            - name: app-config
              readOnly: true
              mountPath: /opt/run/config/

            - name: app-crt
              readOnly: true
              mountPath: /opt/run/crt/

            - name: skywalking-agent
              mountPath: /skywalking

            - name: apm-config
              readOnly: true
              mountPath: /skywalking/agent/config/

            - name: host-time
              readOnly: true
              mountPath: /etc/localtime

          ports:
            - name: http
              protocol: TCP
              containerPort: 80

          env: 
            - name: TZ
              value: Asia/Shanghai

            - name: LANG
              value: en_US.utf8

            - name: SW_AGENT_NAME
              value: __CI_ENVIRONMENT_SLUG__

            - name: RUNTIMEID
              value: __RUNTIMEID__

          envFrom:
            - configMapRef:
                name: url-env
            - configMapRef:
                name: app-env
            - secretRef:
                name: app-env
          resources:
            limits: 
              cpu: __JAVA_CPU__
              memory: __JAVA_RAM__
            requests:
              cpu: 1
              memory: __JAVA_RAM__
```
## Service
```
apiVersion: v1
kind: Service
metadata:
  name: turnright-__CI_ENVIRONMENT_SLUG__
  namespace: __APP_NAMESPACE__
  labels:
    version: __VERSION__
    app: __CI_ENVIRONMENT_SLUG__
    app.kubernetes.io/version: __VERSION__
    app.kubernetes.io/name: vip
  annotations:
    kubesphere.io/serviceType: 'statelessservice'
    servicemesh.kubesphere.io/enabled: 'true'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    version: __VERSION__
    app: __CI_ENVIRONMENT_SLUG__
    app.kubernetes.io/version: __VERSION__
    app.kubernetes.io/name: vip
```
### Ingress 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: 'true'
  name: turnright-__CI_ENVIRONMENT_SLUG__
  namespace: __APP_NAMESPACE__
  labels:
    app.kubernetes.io/version: __VERSION__
    app.kubernetes.io/name: vip
spec:
  ingressClassName: istio
  rules:
    - host: turnright-__CI_ENVIRONMENT_SLUG__.__BRANCH_ALIAS__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: turnright-__CI_ENVIRONMENT_SLUG__
                port:
                  number: 80
```
