### ISSUE TITLE
[Notification Manager] `Receiver` cannot be synchronized to member clusters

### ISSUE THREAD

**Issue by daixijun** [kubesphere/kubesphere#4836]
**Describe the Bug**
<img width="539" alt="image" src="https://user-images.githubusercontent.com/3611220/165783695-f7be2bec-e430-4517-8ddb-da9547110f39.png">
`Receiver` default version is v2beta2, but ks-manager-controller can only synchronizes v2beta1

https://github.com/kubesphere/kubesphere/blob/master/pkg/client/listers/notification/v2beta1/receiver.go#L25

**Versions Used**
KubeSphere: v3.3.0-alpha.2
Kubernetes: v1.20.11
Notification Manager: v1.4.0

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Create `Receiver` to host cluster
```
cat <<EOF | kubectl apply -f-
---
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: user-xijun.dai-wechat-receiver
  labels:
    app: notification-manager
    type: tenant
    user: xijun.dai
spec:
  wechat:
    toUser:
      - "XiJun.Dai@example.com"
EOF
```
2. Try to get 'Receiver' from the member cluster
3. No synchronization 'Receiver' resource is found in the 'ks-controller-manager' log
`kubectl logs -f -n kubesphere-system ks-controller-manager-69c89c4585-jhjnt | grep 'wechat-receiver'`

**Expected behavior**
