### ISSUE TITLE
kubefed-controller-manager  panic

### ISSUE THREAD

**Issue by xiaoping378** [kubesphere/kubesphere#4891]
**Describe the Bug**

if the added cluster's kubeconfig use `insecure-skip-tls-verify: true`, kubefed-controller-manager will be panic, we should validate this case.
```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
```
For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**
