### ISSUE TITLE
Failed to login after upgrage to v3.3.0

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#5008]
**Describe the Bug**

After upgrading to KubeSphere 3.3.0, the cluster environment with multiple master nodes experience multiple failed logins. The ks-apiserver reported the following logs:

![image](https://user-images.githubusercontent.com/8263040/176366491-30e3c141-2b9a-4f44-b996-6454e6afd2f4.png)

Related Chinese Posts: https://kubesphere.com.cn/forum/d/7517-kk221v330workspace

**Versions Used**
KubeSphere: v3.3.0

**Environment**

Multiple master node.

**Comment by wansir** [comment]
Regression bug, related to https://github.com/kubesphere/ks-installer/pull/1991

**Comment by wansir** [comment]
### Solution
Enable Redis manually by the following command

```
kubectl -n kubesphere-system edit cc ks-installer
```

Make sure Redis is enabled.

```
spec:
  common:
    redis:
      enabled: true
      # enable Redis HA
      # enableHA: true
      volumeSize: 2Gi
```
