### ISSUE TITLE
Failed to get token with external OIDC Identity provider.

### ISSUE THREAD

**Issue by expandboard** [kubesphere/kubesphere#5140]
**What's your question**
Keycloak is configured for external OIDC Identity provider. when press login Keycloak button it will redirect to Keycloak login page but when it login it arise this message after redirect to kubesphere url;
```json
{"status":401,"reason":"Unauthorized","message":"Unauthorized: no id_token in token response\n"}
```

after refresh page again shows this;

```json
{"status":401,"reason":"Unauthorized","message":"Unauthorized: oidc: failed to get token: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Code not valid\"}\n"}
```

configuration in ClusterConfiguration is;
```yaml
﻿apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  labels:
    version: v3.3.0
  name: ks-installer
  namespace: kubesphere-system
spec:
  alerting:
    enabled: false
  auditing:
    enabled: false
  authentication:
    authenticateRateLimiterDuration: 10m0s
    authenticateRateLimiterMaxTries: 10
    jwtSecret: ''
    oauthOptions:
      accessTokenInactivityTimeout: 30m
      accessTokenMaxAge: 1h
      identityProviders:
        - mappingMethod: auto
          name: keycloak
          provider:
            clientID: kubesphere
            clientSecret: C2Zfk8k9vxBs7Rt8wa3oNBZGZY5zta37
            idTokenSkipVerify: true
            issuer: 'http://10.8.0.2:31892/realms/demo'
            redirectURL: 'http://10.8.0.2:30880/oauth/redirect/keycloak'
          scopes:
            - openid
            - email
            - profile
          type: OIDCIdentityProvider
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    es:
      basicAuth:
        enabled: false
        password: ''
        username: ''
      data:
        volumeSize: 20Gi
      elkPrefix: logstash
      externalElasticsearchHost: ''
      externalElasticsearchPort: ''
      logMaxAge: 7
      master:
        volumeSize: 4Gi
    gpu:
      kinds:
        - default: true
          resourceName: nvidia.com/gpu
          resourceType: GPU
    minio:
      volumeSize: 20Gi
    monitoring:
      GPUMonitoring:
        enabled: false
      endpoint: 'http://prometheus-operated.kubesphere-monitoring-system.svc:9090'
    openldap:
      enabled: false
    redis:
      enabled: false
  devops:
    enabled: false
    jenkinsJavaOpts_MaxRAM: 2g
    jenkinsJavaOpts_Xms: 1200m
    jenkinsJavaOpts_Xmx: 1600m
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
  edgeruntime:
    enabled: false
    kubeedge:
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ''
        service:
          cloudhubHttpsNodePort: '30002'
          cloudhubNodePort: '30000'
          cloudhubQuicNodePort: '30001'
          cloudstreamNodePort: '30003'
          tunnelNodePort: '30004'
      enabled: false
      iptables-manager:
        enabled: true
        mode: external
  etcd:
    endpointIps: localhost
    monitoring: false
    port: 2379
    tlsEnable: true
  events:
    enabled: false
  gatekeeper:
    enabled: false
  local_registry: ''
  logging:
    enabled: false
    logsidecar:
      enabled: true
      replicas: 2
  metrics_server:
    enabled: false
  monitoring:
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
    node_exporter:
      port: 9100
    storageClass: ''
  multicluster:
    clusterRole: none
  network:
    ippool:
      type: none
    networkpolicy:
      enabled: false
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  persistence:
    storageClass: ''
  servicemesh:
    enabled: false
    istio:
      components:
        cni:
          enabled: false
        ingressGateways:
          - enabled: false
            name: istio-ingressgateway
  terminal:
    timeout: 600
```

OAUTH config by fetching http://10.8.0.2:30880/kapis/config.kubesphere.io/v1alpha2/configs/oauth results this;

```json
{
 "issuer": "kubesphere",
 "identityProviders": [
  {
   "name": "keycloak",
   "mappingMethod": "auto",
   "disableLoginConfirmation": false,
   "type": "OIDCIdentityProvider",
   "provider": {
    "clientID": "kubesphere",
    "endpoint": {
     "authURL": "http://10.8.0.2:31892/realms/demo/protocol/openid-connect/auth",
     "endSessionURL": "http://10.8.0.2:31892/realms/demo/protocol/openid-connect/logout",
     "jwksURL": "http://10.8.0.2:31892/realms/demo/protocol/openid-connect/certs",
     "tokenURL": "http://10.8.0.2:31892/realms/demo/protocol/openid-connect/token",
     "userInfoURL": "http://10.8.0.2:31892/realms/demo/protocol/openid-connect/userinfo"
    },
    "idTokenSkipVerify": true,
    "issuer": "http://10.8.0.2:31892/realms/demo",
    "redirectURL": "http://10.8.0.2:30880/oauth/redirect/keycloak"
   }
  }
 ],
 "clients": [
  {
   "name": "kubesphere",
   "redirectURIs": [
    "*"
   ]
  }
 ],
 "accessTokenMaxAge": 3600000000000,
 "accessTokenInactivityTimeout": 1800000000000
}
```

**Environment: OS & Hardware Information**
+ Ubuntu 20.04.4 LTS
+ 64-bit
+ Memory 7.7 GiB
+ Intel® Core™ i7-8550U CPU @ 1.80GHz × 8 
+ K3S

**Error logs or message (Attach logs or screenshot)**
```json
{"status":401,"reason":"Unauthorized","message":"Unauthorized: no id_token in token response\n"}
```

after refresh page again shows this;

```json
{"status":401,"reason":"Unauthorized","message":"Unauthorized: oidc: failed to get token: oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_grant\",\"error_description\":\"Code not valid\"}\n"}
```

**Installer Version**
 v3.0.0

**Comment by expandboard** [comment]
This issue solved in another test by increasing RAM memory to 10GB in VM and works.👌

**Comment by caiyili** [comment]
同样遇到这个问题，应该是 scope 没有配置、或者配置的层级不对导致的。

````yaml
        - mappingMethod: auto
          name: keycloak
          provider:
            clientID: kubesphere
            clientSecret: C2Zfk8k9vxBs7Rt8wa3oNBZGZY5zta37
            idTokenSkipVerify: true
            issuer: 'http://10.8.0.2:31892/realms/demo'
            redirectURL: 'http://10.8.0.2:30880/oauth/redirect/keycloak'
          scopes:
            - openid
            - email
            - profile
````

这里面 scopes 配置的和 provider 同一层级，需要改到 provider 下一层级

````yaml
        - mappingMethod: auto
          name: keycloak
          provider:
            clientID: kubesphere
            clientSecret: C2Zfk8k9vxBs7Rt8wa3oNBZGZY5zta37
            idTokenSkipVerify: true
            issuer: 'http://10.8.0.2:31892/realms/demo'
            redirectURL: 'http://10.8.0.2:30880/oauth/redirect/keycloak'
            scopes:
              - openid
              - email
              - profile
````

修改完之后，通过 http://$HOST/kapis/config.kubesphere.io/v1alpha2/configs/oauth 来验证是否生效了。

如果没生效，可能需要重启下

````shell
kubectl rollout restart -n kubesphere-system deploy ks-installer
kubectl rollout restart -n kubesphere-system deploy ks-apiserver
````
