### ISSUE TITLE
The OpenLDAP that Kubesphere accesses does not take effect

### ISSUE THREAD

**Issue by Nacho-A** [kubesphere/kubesphere#5185]
KS 3.3.0
OPENLDAP lastest
It's not an LDAP problem,Other systems can log in as LDAP users
Here is my configuration:

```
spec:
 authentication:
    jwtSecret: ''
    maximumClockSkew: 10s
    multipleLogin: true
    oauthOptions:
      accessTokenMaxAge: 1h
      accessTokenInactivityTimeout: 30m
      identityProviders:
      - name: LDAP
        type: LDAPIdentityProvider
        mappingMethod: auto
        provider:
          host: xxxxxx:389
          managerDN: 'cn=admin,dc=xxx,dc=com'
          managerPassword: xxx
          userSearchBase: 'dc=xxx,dc=com'
          loginAttribute: cn
          mailAttribute: Email
```

**Comment by a52074137** [comment]
完全一样的配置，把KS集群版本降级到3.2.1就可以了，希望尽快解决

**Comment by wansir** [comment]
There have been no changes since v3.2.1. The logs of ks-apiserver are useful, could you provide more information about this?

**Comment by a52074137** [comment]
![image](https://user-images.githubusercontent.com/67043152/188078085-3f638d33-d66f-4b42-8ec6-184b3fac46b8.png)

**Comment by a52074137** [comment]
Right now I am using two KS3.3 clusters and the LDAP configuration is invalid
Demoting one of the clusters to 3.2.1 takes effect
The LDAP configuration has never changed

**Comment by whensuc** [comment]
me too

**Comment by a52074137** [comment]
Does anyone have a solution? It's urgent

**Comment by a52074137** [comment]
@zhou1203 @wenxin-01

**Comment by wenxin-01** [comment]
I used the same configuration to succeed in ks3.2.1 and ks3.3.1, it is recommended to restart the server and try again. @a52074137 
```
authentication:
    jwtSecret: ''
    maximumClockSkew: 10s
    multipleLogin: true
    oauthOptions:
      accessTokenInactivityTimeout: 30m
      accessTokenMaxAge: 1h
      identityProviders:
        - mappingMethod: auto
          name: LDAP
          provider:
            host: 'xxxxx:32028'
            loginAttribute: uid
            mailAttribute: mail
            managerDN: 'cn=admin,dc=test,dc=test'
            managerPassword: '123456'
            userSearchBase: 'ou=kubesphere,dc=test,dc=test'
          type: LDAPIdentityProvider
```
