### ISSUE TITLE
KubeSphere doesn't support LDAP anonymous configuration

### ISSUE THREAD

**Issue by lucumt** [kubesphere/kubesphere#5195]
**Versions Used**
KubeSphere: v3.1.1

**What's it about?**
When integrate `LDAP` into KubeSphere,we must specify `managerDN` and `managerPassword`,it doesn't support  anonymous  configuration.

if we config `LDAP` without `managerDN` and `managerPassword`, we can not login success.

* login result:
  ![image](https://user-images.githubusercontent.com/5226038/188300200-4bf64dba-0ca9-4e3b-ab6c-ce03fd91f420.png)
* config code：
     ```yml
  spec:
    authentication:
      jwtSecret: ''
      maximumClockSkew: 10s
      multipleLogin: true
      oauthOptions:
        accessTokenMaxAge: 1h
        accessTokenInactivityTimeout: 30m
        identityProviders:
        - name: LDAP
          type: LDAPIdentityProvider
          mappingMethod: auto
          provider:
            host: 192.168.0.2:389
            userSearchBase: cn=users,dc=nas
            loginAttribute: uid
            mailAttribute: mail
  ```

I believe this is an important feature for Kubesphere. There're a few use cases:

* Some company do not provide manager account for `LDAP`,they only allow anonymous config.
* For security reason, sometimes using manager account is forbidden, and anonymous config is the left option.

**Area Suggestion**
Hope can support `LDAP` anonymous config  and login(in other words make `managerDN` and `managerPassword` not required),such as below:
```yml
spec:
  authentication:
    jwtSecret: ''
    maximumClockSkew: 10s
    multipleLogin: true
    oauthOptions:
      accessTokenMaxAge: 1h
      accessTokenInactivityTimeout: 30m
      identityProviders:
      - name: LDAP
        type: LDAPIdentityProvider
        mappingMethod: auto
        provider:
          host: 192.168.0.2:389
          # managerDN and managerPassword is not required when using anonymous
          # managerDN: uid=root,cn=users,dc=nas
          # managerPassword: ********
          userSearchBase: cn=users,dc=nas
          loginAttribute: uid
          mailAttribute: mail
```
