### ISSUE TITLE
calico installation error

### ISSUE THREAD

**Issue by NKDYX** [kubesphere/kubesphere#5272]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**What's your question**
when running ```/kk create cluster -f config-sample.yaml```,i had meet this error:
``` shell
error: unable to recognize "/etc/kubernetes/network-plugin.yaml": no matches for kind "PodDisruptionBudget" in version "policy/v1": Process exited with status 1
15:58:52 CST failed: [master]
error: Pipeline[CreateClusterPipeline] execute failed: Module[DeployNetworkPluginModule] exec failed: 
failed: [master] [DeployCalico] exec failed after 5 retires: deploy network plugin failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl apply -f /etc/kubernetes/network-plugin.yaml --force" 
```
**Environment: OS & Hardware Information**
VMware ubuntu 22.04  4 Core 04G 20G
use kubernetes v1.19.7 kubesphere  3.3.0

and i have figure that out: the version of calico is not perfectly fit your kk, so here is way to deal with it :
 I must change the ```/etc/kubernetes/network-plugin.yaml``` when kk running ,because i am not sure where you store that calico.yaml in the tar.gz file. 
```
# original
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers

# change to the following 
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: calico-kube-controllers
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
```
if you are not change it when running ,the  ./kk will give a new calico.yaml to ```/etc/kubernetes/network-plugin.yaml```, so a better way to let us know where these file be would take further steps for users 

and here is the new calico yaml file link to know more about this problem:
``` shell
curl https://docs.projectcalico.org/v3.20/manifests/calico.yaml -O
vim calico.yaml
```

**Comment by renyunkang** [comment]
Do you want to use a custom version of calico when installing kubesphere with kk? 
if yes, you can set the spec.network.plugin: none, and specify the calico information installed in the addons.

```yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  ... ...
  network:
    plugin: none
  ... ...
  addons: 
  - name: calico
    namespace: kube-system
    sources:
      yaml:
        path:
        - /mycluster/calico.yaml  # or  https://docs.projectcalico.org/v3.20/manifests/calico.yaml
```

more about kubekey addons:  https://github.com/kubesphere/kubekey/blob/master/docs/addons.md
