### ISSUE TITLE
v3.3.0版本部署ExternalName类型的Service后，无法加载该namespace的'工作负载-服务'页面

### ISSUE THREAD

**Issue by ghost** [kubesphere/kubesphere#5292]
**Describe the Bug**
部署了一个类型为`ExternalName`的<b>Service</b>后，无法再进入`工作负载` - `服务`页面

**Versions Used**
KubeSphere:  v3.3.0

**Environment**
Ubuntu1804 / 1 masters:  8cpu/20g; 4 nodes: 8cpu/20g

**How To Reproduce**
新增一个service.yaml
```
kind: Service
apiVersion: v1
metadata:
  name: nacos
  namespace: namespace2
spec:
  type: ExternalName
  externalName: nacos.default.svc.cluster.local
  ports:
  - port: 8848
```
部署service
```
kubectl apply -f service.yaml
```
![image](https://user-images.githubusercontent.com/110509161/195753807-8230513f-0df5-4038-b6ef-8dc381439b35.png)
