### ISSUE TITLE
Can't access `KubeSphere` console after machine reboot

### ISSUE THREAD

**Issue by Dgotlieb** [kubesphere/kubesphere#5343]
**Describe the Bug**
After setting up HA cluster (3 nodes with `etcd` & `control-plane`), the console stuck on loading after node rebbot. 

**Versions Used**
KubeSphere: `v3.3.1`
Kubernetes: `v1.22.10`

**Environment**
3 nodes 64GB Ram / 40 cores
OS: Ubuntu 20.04.5 LTS

**How To Reproduce**
1. Bootstrap your cluster (e.g: `./kk create cluster --with-kubernetes v1.22.10 --with-kubesphere v3.2.1 -f cluster.yaml`)

``` yaml
apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - { name: node01, address: 10.200.4.10, internalAddress: 10.200.4.10, port: 22, user: admin, password: "password" }
  - { name: node02, address: 10.200.4.11, internalAddress: 10.200.4.11, port: 22, user: admin, password: "password" }
  - { name: node03, address: 10.200.4.11, internalAddress: 10.200.4.11, port: 22, user: admin, password: "password" }
  roleGroups:
    etcd:
    - node01
    - node02
    - node03
    control-plane:
    - node01
    - node02
    - node03
    worker:
    - node01
    - node02
    - node03
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.22.10
    clusterName: cluster.local
    autoRenewCerts: true
    containerManager: containerd
  etcd:
    type: kubekey
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    multusCNI:
      enabled: false
  registry:
    privateRegistry: ""
    namespaceOverride: ""
    registryMirrors: []
    insecureRegistries: []
  addons: []

---
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.3.1
spec:
  persistence:
    storageClass: ""
  authentication:
    jwtSecret: ""
  zone: ""
  local_registry: ""
  namespace_override: ""
  # dev_tag: ""
  etcd:
    monitoring: true
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    # apiserver:
    #  resources: {}
    # controllerManager:
    #  resources: {}
    redis:
      enabled: true
      enableHA: true
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      # type: external
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: "nvidia.com/gpu"
        resourceType: "GPU"
        default: true
    es:
      # master:
      #   volumeSize: 4Gi
      #   replicas: 1
      #   resources: {}
      # data:
      #   volumeSize: 20Gi
      #   replicas: 1
      #   resources: {}
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ""
        password: ""
      externalElasticsearchHost: ""
      externalElasticsearchPort: ""
  alerting:
    enabled: false
    # thanosruler:
    #   replicas: 1
    #   resources: {}
  auditing:
    enabled: true
    # operator:
    #   resources: {}
    # webhook:
    #   resources: {}
  devops:
    enabled: false
    # resources: {}
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 1200m
    jenkinsJavaOpts_Xmx: 1600m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
    # operator:
    #   resources: {}
    # exporter:
    #   resources: {}
    # ruler:
    #   enabled: true
    #   replicas: 2
    #   resources: {}
  logging:
    enabled: false
    logsidecar:
      enabled: true
      replicas: 2
      # resources: {}
  metrics_server:
    enabled: false
  monitoring:
    storageClass: ""
    node_exporter:
      port: 9100
      # resources: {}
    # kube_rbac_proxy:
    #   resources: {}
    # kube_state_metrics:
    #   resources: {}
    # prometheus:
    #   replicas: 1
    #   volumeSize: 20Gi
    #   resources: {}
    #   operator:
    #     resources: {}
    # alertmanager:
    #   replicas: 1
    #   resources: {}
    # notification_manager:
    #   resources: {}
    #   operator:
    #     resources: {}
    #   proxy:
    #     resources: {}
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
        # resources: {}
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: true
  servicemesh:
    enabled: false
    istio:
      components:
        ingressGateways:
        - name: istio-ingressgateway
          enabled: false
        cni:
          enabled: false
  edgeruntime:
    enabled: false
    kubeedge:
      enabled: false
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ""
        service:
          cloudhubNodePort: "30000"
          cloudhubQuicNodePort: "30001"
          cloudhubHttpsNodePort: "30002"
          cloudstreamNodePort: "30003"
          tunnelNodePort: "30004"
        # resources: {}
        # hostNetWork: false
      iptables-manager:
        enabled: true
        mode: "external"
        # resources: {}
      # edgeService:
      #   resources: {}
  terminal:
    timeout: 600
```

2. Wait for all pods to run properly:
``` bash
administrator@node01: $ kubectl get pods -n kube-system
NAME                                           READY   STATUS    RESTARTS   AGE
calico-kube-controllers-69d878584c-dv2mj       1/1     Running   0          6m29s
calico-node-hb27t                              1/1     Running   0          6m30s
calico-node-mzc9r                              1/1     Running   0          6m30s
calico-node-t55l4                              1/1     Running   0          6m30s
calico-node-vs6bk                              1/1     Running   0          6m30s
coredns-b5648d655-hcd7f                        1/1     Running   0          6m53s
coredns-b5648d655-xlxpl                        1/1     Running   0          6m53s
haproxy-node01                               1/1     Running   0          6m20s
kube-apiserver-node01                         1/1     Running   0          6m40s
kube-apiserver-node02                         1/1     Running   0          7m2s
kube-apiserver-node03                        1/1     Running   0          6m41s
kube-controller-manager-node01                1/1     Running   0          6m40s
kube-controller-manager-node02                1/1     Running   0          7m3s
kube-controller-manager-node03               1/1     Running   0          6m41s
kube-proxy-4qc86                               1/1     Running   0          6m30s
kube-proxy-5nfxb                               1/1     Running   0          6m30s
kube-proxy-q2nsk                               1/1     Running   0          6m30s
kube-proxy-znh99                               1/1     Running   0          6m30s
kube-scheduler-node01                         1/1     Running   0          6m40s
kube-scheduler-node02                         1/1     Running   0          7m3s
kube-scheduler-node03                        1/1     Running   0          6m41s
nodelocaldns-4fv5b                             1/1     Running   0          6m54s
nodelocaldns-4rqj9                             1/1     Running   0          6m41s
nodelocaldns-dm682                             1/1     Running   0          6m34s
nodelocaldns-z94sn                             1/1     Running   0          6m42s
openebs-localpv-provisioner-57bbf864d5-wggpl   1/1     Running   0          6m27s
snapshot-controller-0                          1/1     Running   0          5m32s
```

``` bash
administrator@node01: $ kubectl get pods -n kubesphere-system
NAME                                     READY   STATUS    RESTARTS   AGE
ks-apiserver-7467d5dd86-2qsk2            1/1     Running   0          2m9s
ks-apiserver-7467d5dd86-42czt            1/1     Running   0          2m41s
ks-apiserver-7467d5dd86-xmh9g            1/1     Running   0          3m30s
ks-console-65f4d44d88-5q8cm              1/1     Running   0          4m53s
ks-console-65f4d44d88-8dh4k              1/1     Running   0          4m53s
ks-console-65f4d44d88-fn8d5              1/1     Running   0          4m53s
ks-controller-manager-85d95d7cf8-jlw7k   1/1     Running   0          3m30s
ks-controller-manager-85d95d7cf8-lddws   1/1     Running   0          2m8s
ks-controller-manager-85d95d7cf8-vdpn8   1/1     Running   0          2m17s
ks-installer-85c7b67967-8zcvr            1/1     Running   0          7m4s
redis-ha-haproxy-868fdbddd4-8956l        1/1     Running   0          5m53s
redis-ha-haproxy-868fdbddd4-f9bqx        1/1     Running   0          5m53s
redis-ha-haproxy-868fdbddd4-z2z7c        1/1     Running   0          5m53s
redis-ha-server-0                        2/2     Running   0          5m53s
redis-ha-server-1                        2/2     Running   0          5m33s
redis-ha-server-2                        2/2     Running   0          5m18s
```

3. Reboot any machine:
``` bash
administrator@node01: $ sudo reboot
```

**Results**
1. No access via Console (port 30880) - loader is stuck
![image](https://user-images.githubusercontent.com/12662834/198999742-57801478-9dff-4fae-ba9d-4998bce9d669.png)

2. `ks-apiserver` keep crashing  
``` bash 
administrator@node01:$ kubectl logs ks-apiserver-7467d5dd86-lwgld -n kubesphere-system
W1031 11:42:14.242263       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1031 11:42:14.245663       1 client_config.go:615] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W1031 11:42:14.269514       1 metricsserver.go:238] Metrics API not available.
Error: failed to connect to redis service, please check redis status, error: dial tcp: i/o timeout
2022/10/31 11:42:19 failed to connect to redis service, please check redis status, error: dial tcp: i/o timeout
```

3. `redis-ha-haproxy` pod not starting with the below log: 
``` bash
administrator@node01:$ kubectl logs redis-ha-haproxy-868fdbddd4-gqml2 -n kubesphere-system
Error from server (BadRequest): container "haproxy" in pod "redis-ha-haproxy-868fdbddd4-gqml2" is waiting to start: 
PodInitializing
```

4. No error logs in `kubelet`, `etcd` (system service)

**Expected behavior**
Console to load properly

**Extra info**
1. I followed the [login failure doc](https://kubesphere.io/docs/v3.3/faq/access-control/cannot-login/) with no success
2. All of my workloads seem to run properly
3. I tried this flow on a few machines with the same result
4. Deleting `kubesphere` (using the [kubesphere-delete script](https://github.com/kubesphere/ks-installer/blob/master/scripts/kubesphere-delete.sh)) and re-installing kubesphere solved the issue
