### ISSUE TITLE
ks-console's service type become NodePort as default after enabling logging plugin

### ISSUE THREAD

**Issue by Huangvivi** [kubesphere/kubesphere#5361]
ks version: 3.3.1
k8s env: GKE

After installing ks on GKE, I change the service type from NodePort to LoadBalacer as [Document](https://kubesphere.com.cn/en/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-gke) said.

Then I enabled the logging plugin by editing CRDS (clusterconfiguration) 
```
 logging:
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2

    es:
      basicAuth:
        enabled: true
        password: 'xxxxxxx'
        username: elastic
      elasticsearchDataReplicas: 2
      elasticsearchDataVolumeSize: 300Gi
      elasticsearchMasterReplicas: 1
      elasticsearchMasterVolumeSize: 300Gi
      elkPrefix: logstash
      externalElasticsearchHost: 'https://my-es-http.default.svc.cluster.local'
      externalElasticsearchPort: '9200'
      logMaxAge: 7
```

Then click "OK" to save. After a while, the service type of `ks-console` become the default value: "NodePort". I need to 
change it to "LoadBalancer" again to access KS .

I have no idea that if this going to happen again by enabling others plugin, but it should be a little problem.
