### ISSUE TITLE
Default platform role for new users 

### ISSUE THREAD

**Issue by nickpodobiedov** [kubesphere/kubesphere#5373]
**Describe the Bug**
Cannot assign default platform role for user created from Okta authenticator.

**Versions Used**
KubeSphere: v3.2.1
Kubernetes: Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}

**Environment**
57 nodes with different type. [Amazon Linux 2]

I have the config for Okta connecting:
```
oauthOptions:
  clients:
  - name: kubesphere
    redirectURIs:
    - '*'
    secret: kubesphere
  identityProviders:
  - mappingMethod: auto
    name: okta
    provider:
      clientID: <REMOVED>
      clientSecret: <REMOVED>
      issuer: <REMOVED>
      redirectURL: <REMOVED>
      - openid
      - email
      - profile
    type: OIDCIdentityProvider
```
It works, I can login from the Okta, but new user was created without any `Platform role`. 
Question:
1. Can I setup default platform role for new users?
2. Can I inherit Okta user group name to platform role inside the Kubesphere?

**How To Reproduce**
1. Install cluster.
2. Configure Okta connection.
3. Connect to the Kubesphere through the Okta.

**Expected behavior**
New user have some platform role at once it logged in from Okta first time.
New user at once get platform role with name according his Okta group.
