### ISSUE TITLE
Deploy the application to the edge node to automatically add toleration

### ISSUE THREAD

**Issue by sdnmw** [kubesphere/kubesphere#5421]
**What's it about?**

After kubeedge is enabled, when the user deploys an application to the edge and selects an edge node, toleration is automatically added to the application yaml to deal with the taints of the edge node.
**What's the reason why we need it?**

For convenience and platform automation, it is recommended to reduce the operations that allow users to edit the yaml tolerance individually after creating an edge application, and  automatically add tolerance in the background after user specify an edge node. In order to reduce the cost of learning, highlight the automation advantages of the platform's autonomous edge node scheduling.

For example, from

```
      nodeSelector:
        kubernetes.io/hostname: edgenode-1
```
to
```
      nodeSelector:
        kubernetes.io/hostname: edgenode-1
      tolerations:
        - key: node-role.kubernetes.io/edge
          operator: Exists
          effect: NoSchedule
```
I believe this is an important feature for Kubesphere. There're a few use cases:

* One-click deployment of edge applications

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request
