### ISSUE TITLE
Kubesphere does not support grpc probe health check

### ISSUE THREAD

**Issue by imyuanandyou** [kubesphere/kubesphere#5439]
**Describe the Bug**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/?spm=a2c4g.11186623.0.0.4841229cTTUstn#define-a-grpc-liveness-probe
Kubernetes supports gRPC survival probe in version 1.24. When I define the gRPC survival probe, the pod console of kubesphere web will be blank and an error will be reported
```
       livenessProbe:
         failureThreshold: 3
         grpc:
           port: 7001
           service: ""
         initialDelaySeconds: 20
         periodSeconds: 15
         successThreshold: 1
         timeoutSeconds: 2
       readinessProbe:
         failureThreshold: 3
         grpc:
           port: 7001
           service: ""
         initialDelaySeconds: 10
         periodSeconds: 3
         successThreshold: 1
         timeoutSeconds: 2
```

**Versions Used**
KubeSphere: v3.3.0
Kubernetes: 1.25

**Expected behavior**
The web console can display correctly

The url I visited：org/clusters/default/projects/xxx-server/statefulsets/app-xxxx/resource-status
<img width="1670" alt="kubesphere" src="https://user-images.githubusercontent.com/26473927/210513459-2caf088c-e603-4130-9886-32bde4b06b53.png">
