### ISSUE TITLE
3.3.1 default setup doesn't work with 1.24.8 (Microk8s)

### ISSUE THREAD

**Issue by fzhan** [kubesphere/kubesphere#5485]
**Describe the Bug**
After default setup through ks-installer, with all the component enabled, cluster configured with external prometheus failed to obtain cluster information.

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: 3.3.1
Kubernetes: 1.24.8

**Environment**
How many nodes and their hardware configuration:
Ubuntu 22.04, microk8s 1.24.8, cluster has 5 nodes with 8 cores each, 64 GB of RAM and 1T storage

**Expected behavior**
Cluster detail page should get the details usage of CPU/RAM.

# ClusterConfiguration: #
```
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"installer.kubesphere.io/v1alpha1","kind":"ClusterConfiguration","metadata":{"annotations":{},"labels":{"version":"v3.3.1"},"name":"ks-installer","namespace":"kubesphere-system"},"spec":{"alerting":{"enabled":false},"auditing":{"enabled":false},"authentication":{"jwtSecret":""},"common":{"apiserver":{"resources":{"requests":{"cpu":2,"memory":"2G"}}},"controllerManager":{"resources":{}},"core":{"console":{"enableMultiLogin":true,"port":30880,"type":"NodePort"}},"es":{"basicAuth":{"enabled":false,"password":"","username":""},"elkPrefix":"logstash","externalElasticsearchHost":"elasticsearch-logging.kube-system.svc","externalElasticsearchPort":"9200","logMaxAge":7},"gpu":{"kinds":[{"default":false,"resourceName":"nvidia.com/gpu","resourceType":"GPU"}]},"minio":{"volumeSize":"20Gi"},"monitoring":{"GPUMonitoring":{"enabled":false},"endpoint":"http://prometheus-k8s.monitoring.svc:9090","type":"external"},"openldap":{"enabled":true,"volumeSize":"2Gi"},"redis":{"enableHA":true,"enabled":true,"volumeSize":"2Gi"}},"devops":{"enabled":false,"jenkinsMemoryLim":"8Gi","jenkinsMemoryReq":"4Gi","jenkinsVolumeSize":"8Gi"},"edgeruntime":{"enabled":false,"kubeedge":{"cloudCore":{"cloudHub":{"advertiseAddress":[""]},"service":{"cloudhubHttpsNodePort":"30002","cloudhubNodePort":"30000","cloudhubQuicNodePort":"30001","cloudstreamNodePort":"30003","tunnelNodePort":"30004"}},"enabled":false,"iptables-manager":{"enabled":true,"mode":"external"}}},"etcd":{"endpointIps":"localhost","monitoring":false,"port":2379,"tlsEnable":true},"events":{"enabled":false},"gatekeeper":{"enabled":false},"local_registry":"","logging":{"enabled":true,"logsidecar":{"enabled":true,"replicas":2}},"metrics_server":{"enabled":false},"monitoring":{"gpu":{"nvidia_dcgm_exporter":{"enabled":false}},"node_exporter":{"port":9100},"storageClass":""},"multicluster":{"clusterRole":"none"},"network":{"ippool":{"type":"none"},"networkpolicy":{"enabled":false},"topology":{"type":"none"}},"openpitrix":{"store":{"enabled":true}},"persistence":{"storageClass":"rook-cephfs"},"servicemesh":{"enabled":false,"istio":{"components":{"cni":{"enabled":true},"ingressGateways":[{"enabled":true,"name":"istio-ingressgateway"}]}}},"terminal":{"timeout":600}}}
  labels:
    version: v3.3.1
  name: ks-installer
  namespace: kubesphere-system
spec:
  alerting:
    enabled: false
  auditing:
    enabled: false
  authentication:
    jwtSecret: ''
  common:
    apiserver:
      resources:
        requests:
          cpu: 2
          memory: 2G
    controllerManager:
      resources: {}
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    es:
      basicAuth:
        enabled: false
        password: ''
        username: ''
      data:
        volumeSize: 20Gi
      elkPrefix: logstash
      externalElasticsearchHost: elasticsearch-logging.kube-system.svc
      externalElasticsearchPort: '9200'
      logMaxAge: 7
      master:
        volumeSize: 4Gi
    gpu:
      kinds:
        - default: false
          resourceName: nvidia.com/gpu
          resourceType: GPU
    minio:
      volumeSize: 20Gi
    monitoring:
      GPUMonitoring:
        enabled: false
      endpoint: 'http://prometheus-k8s.monitoring.svc:9090'
      type: external
    openldap:
      enabled: true
      volumeSize: 2Gi
    redis:
      enableHA: true
      enabled: true
      volumeSize: 2Gi
  devops:
    enabled: false
    jenkinsMemoryLim: 8Gi
    jenkinsMemoryReq: 4Gi
    jenkinsVolumeSize: 8Gi
  edgeruntime:
    enabled: false
    kubeedge:
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ''
        service:
          cloudhubHttpsNodePort: '30002'
          cloudhubNodePort: '30000'
          cloudhubQuicNodePort: '30001'
          cloudstreamNodePort: '30003'
          tunnelNodePort: '30004'
      enabled: false
      iptables-manager:
        enabled: true
        mode: external
  etcd:
    endpointIps: localhost
    monitoring: false
    port: 2379
    tlsEnable: true
  events:
    enabled: false
  gatekeeper:
    enabled: false
  local_registry: ''
  logging:
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
  metrics_server:
    enabled: false
  monitoring:
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
    node_exporter:
      port: 9100
    storageClass: ''
  multicluster:
    clusterRole: none
  network:
    ippool:
      type: none
    networkpolicy:
      enabled: false
    topology:
      type: none
  openpitrix:
    store:
      enabled: true
  persistence:
    storageClass: rook-cephfs
  servicemesh:
    enabled: false
    istio:
      components:
        cni:
          enabled: true
        ingressGateways:
          - enabled: true
            name: istio-ingressgateway
  terminal:
    timeout: 600
```
# Dashboard 
<img width="849" alt="image" src="https://user-images.githubusercontent.com/894804/212589326-4528cede-5c56-4715-9d67-3c51bdd0b3c4.png">

# Cluster Node 
<img width="873" alt="image" src="https://user-images.githubusercontent.com/894804/212589383-d704c0da-937d-48e5-a649-e5ae5200643f.png">

# Component status 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/894804/212589437-d1ce1457-d185-4f80-bad5-bd4eb3e4f586.png">

# Prometheus status
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/894804/212589564-c65d593d-720f-4319-bbc2-27b5d4b2435e.png">

## Some log on the prometheus pod:

```
2023-01-16T11:01:30.405752262+08:00 level=warn ts=2023-01-16T03:01:30.405Z caller=manager.go:601 component="rule manager" group=kubelet.rules msg="Evaluating rule failed" rule="record: node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile\nexpr: histogram_quantile(0.9, sum by(instance, le) (rate(kubelet_pleg_relist_duration_seconds_bucket[5m]))\n  * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"})\nlabels:\n  quantile: \"0.9\"\n" err="found duplicate series for the match group {instance=\"10.0.0.20:10250\"} on the right hand-side of the operation: [{__name__=\"kubelet_node_name\", instance=\"10.0.0.20:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"a.tengen3.cn\"}, {__name__=\"kubelet_node_name\", endpoint=\"https-metrics\", instance=\"10.0.0.20:10250\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"kube-system\", node=\"a.tengen3.cn\", service=\"kubelet\"}];many-to-many matching not allowed: matching labels must be unique on one side"
```

# Cluster Status
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/894804/212590324-85c7c229-8b46-47aa-885b-86b200fd1790.png">
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/894804/212590357-c246508b-a7be-4316-a987-006527bf0c93.png">
<img width="1600" alt="image" src="https://user-images.githubusercontent.com/894804/212590388-407ad88c-c687-4334-8e74-c764ca431f1a.png">
<img width="1603" alt="image" src="https://user-images.githubusercontent.com/894804/212590402-a234afe5-13a5-4aac-bdb4-8b810a335105.png">
