### ISSUE TITLE
Error external OIDC, Unauthorized: identity provider not found

### ISSUE THREAD

**Issue by GatoSnake** [kubesphere/kubesphere#5647]
**Describe the Bug**
An external identity provider (OIDC) has been registered with Kubesphere, specifically Safenet Trusted Access. When Kubesphere redirects to the STA portal, performs the authentication, and then redirects me to kubesphere (via redirect URL), it gives me the following message:

`URI: https://<DOMAIN>/oauth/redirect/staoidc?state=staoidc&session_state=e20e60b1-8ed1-42a9-936b-ef99ece41127&code=9b0961....`

`{"status":401,"reason":"Unauthorized","message":"Unauthorized: identity provider not found\n"}`

The ks-installer configuration is the following:
```yaml
authentication:
    authenticateRateLimiterDuration: 10m0s
    authenticateRateLimiterMaxTries: 10
    jwtSecret: ''
    oauthOptions:
      accessTokenInactivityTimeout: 30m
      accessTokenMaxAge: 1h
      identityProviders:
        - mappingMethod: auto
          name: staoidc
          provider:
            clientID: xxxxx
            clientSecret: xxxxxx
            endpoint:
              authURL: >-
                 <url_oidc_base>/protocol/openid-connect/auth
              endSessionURL: >-
                 <url_oidc_base>/protocol/openid-connect/logout
              jwksURL: >-
                 <url_oidc_base>/protocol/openid-connect/certs
              tokenURL: >-
                <url_oidc_base>protocol/openid-connect/token
              userInfoURL: >-
                <url_oidc_base>/protocol/openid-connect/userinfo
            issuer: ' <url_oidc_base>'
            redirectURL: 'https://<domain>/oauth/redirect/staoidc'
          type: OIDCIdentityProvider
```

<img width="908" alt="image" src="https://user-images.githubusercontent.com/2672846/233766097-15394a4f-c893-48e9-92cc-3c51ee30658a.png">

**Versions Used**
KubeSphere:
Kubernetes: 3.3.2

**Environment**
How many nodes and their hardware configuration:

OCI Oracle Kubernetes Engine
3 nodes -> 2 cpu, 8 gb every node
