### ISSUE TITLE
Tracing logs missing

### ISSUE THREAD

**Issue by jinqinn** [kubesphere/kubesphere#5676]
**Describe the Bug**
I created bookinfo application with an internal DNS - demo.xx.cc, and Application Governance enabled.
Traffic Management monitoring data works well, but Tracing doesnot.
https://kubesphere.io/forum/assets/files/2023-05-10/1683702456-24011-image.png
https://kubesphere.io/forum/assets/files/2023-05-10/1683702478-954394-image.png

I tried to send requests to productpage service with following command:
`curl http://demo.xx.cc -H 'X-Request-ID: 56955ffa-4000-9e1e-bd53-50a41b825ea0`
, then i can see some tracing logs on Tracing page:
https://kubesphere.io/forum/assets/files/2023-05-10/1683702580-289708-image.png

Bookinfo ingress:
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: bookinfo-ingress
  namespace: demo-project
  labels:
    app.kubernetes.io/name: bookinfo
    app.kubernetes.io/version: v1
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: 'true'
    nginx.ingress.kubernetes.io/upstream-vhost: productpage.demo-project.svc.cluster.local
    kubesphere.io/creator: admin
spec:
  rules:
    - host: demo.xx.cc
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: productpage
                port:
                  number: 9080
```

**Versions Used**
KubeSphere: V3.2.1
Kubernetes: V1.21
