### ISSUE TITLE
[redis-haproxy]how to close ha mode in kubesphere v3.2.1

### ISSUE THREAD

**Issue by lsyLearn** [kubesphere/kubesphere#5805]
When installing Kubesphere v3.2.1 on dual master nodes, redis and haproxy are automatically installed. 
How can I modify the Kubesphere installation configuration to disable the installation of these two components,

the question：
```
kubesphere-system              redis-ha-haproxy-66f9c44d99-bcxs9                        0/1     Init:ImagePullBackOff   0                45m
kubesphere-system              redis-ha-haproxy-66f9c44d99-r79vz                        0/1     Init:ImagePullBackOff   0                45m
kubesphere-system              redis-ha-haproxy-66f9c44d99-vvb48                        0/1     Pending                 0                45m
kubesphere-system              redis-ha-server-0                                        0/2     Init:ImagePullBackOff   0                45m
```

the cluster-configuration.yaml：
```
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  name: ks-installer
  namespace: kubesphere-system
  labels:
    version: v3.2.1
spec:
  persistence:
    storageClass: ''
  authentication:
    jwtSecret: ''
  local_registry: registry.futureedge.com:5000
  etcd:
    monitoring: false
    endpointIps: localhost
    port: 2379
    tlsEnable: true
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    redis:
      enabled: false
      enableHA: false
      volumeSize: 2Gi
    openldap:
      enabled: false
      volumeSize: 2Gi
    minio:
      volumeSize: 20Gi
    monitoring:
      endpoint: http://prometheus-operated.kubesphere-monitoring-system.svc:9090
      GPUMonitoring:
        enabled: false
    gpu:
      kinds:
      - resourceName: nvidia.com/gpu
        resourceType: GPU
        default: true
    es:
      logMaxAge: 7
      elkPrefix: logstash
      basicAuth:
        enabled: false
        username: ''
        password: ''
      externalElasticsearchUrl: ''
      externalElasticsearchPort: ''
  alerting:
    enabled: true
  auditing:
    enabled: false
  devops:
    enabled: false
    jenkinsMemoryLim: 2Gi
    jenkinsMemoryReq: 1500Mi
    jenkinsVolumeSize: 8Gi
    jenkinsJavaOpts_Xms: 512m
    jenkinsJavaOpts_Xmx: 512m
    jenkinsJavaOpts_MaxRAM: 2g
  events:
    enabled: false
  logging:
    enabled: false
    containerruntime: docker
    logsidecar:
      enabled: true
      replicas: 2
  metrics_server:
    enabled: false
  monitoring:
    storageClass: ''
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
  multicluster:
    clusterRole: none
  network:
    networkpolicy:
      enabled: false
    ippool:
      type: none
    topology:
      type: none
  openpitrix:
    store:
      enabled: true
  servicemesh:
    enabled: false
  kubeedge:
    enabled: false
    cloudCore:
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      tolerations: []
      cloudhubPort: '10000'
      cloudhubQuicPort: '10001'
      cloudhubHttpsPort: '10002'
      cloudstreamPort: '10003'
      tunnelPort: '10004'
      cloudHub:
        advertiseAddress:
        - ''
        nodeLimit: '100'
      service:
        cloudhubNodePort: '30000'
        cloudhubQuicNodePort: '30001'
        cloudhubHttpsNodePort: '30002'
        cloudstreamNodePort: '30003'
        tunnelNodePort: '30004'
    edgeWatcher:
      nodeSelector:
        node-role.kubernetes.io/worker: ''
      tolerations: []
      edgeWatcherAgent:
        nodeSelector:
          node-role.kubernetes.io/worker: ''
        tolerations: []

```
