### ISSUE TITLE
创建企业空间的 restful 接口

### ISSUE THREAD

**Issue by DustFinger001** [kubesphere/kubesphere#584]
请问现在没有创建企业空间的 restful 接口吗；我查了 swagger 和官方文档都没有，后台运维脚本或者其他服务调用到这个接口要怎么处理呢？
ps： 希望 kubesphere 管理界面的功能在 restful 接口中都能开放；这样，使用自有的应用和kubesphere 管理功能的时候就能无缝对接了。

**Comment by zryfish** [comment]
目前企业空间是一个crd对象，对应的文档我们正在整理生成。如果着急使用，可以借助kubectl 来看下对应的 api 请求.

```
~#: cat ws.yaml
apiVersion: tenant.kubesphere.io/v1alpha1
kind: Workspace
metadata:
  annotations:
    creator: admin
  name: test
spec:
  manager: admin

~#: kubectl create -f ws.yaml --v 9

curl -k -v -XPOST  -H "Accept: application/json" -H "Content-Type: application/json" -H "User-Agent: kubectl/v1.13.5 (linux/amd64) kubernetes/2166946" 'https://k8s:6443/apis/tenant.kubesphere.io/v1alpha1/workspaces'

Request Body: {"apiVersion":"tenant.kubesphere.io/v1alpha1","kind":"Workspace","metadata":{"annotations":{"creator":"admin"},"name":"test"},"spec":{"manager":"admin"}}
```
workspace的 spec 在这里 https://github.com/kubesphere/kubesphere/blob/master/pkg/apis/tenant/v1alpha1/workspace_types.go
