### ISSUE TITLE
I added an EKS cluster in kubesphere 3.3, and the cluster status keeps prompting **not ready**

### ISSUE THREAD

**Issue by jasontom147** [kubesphere/kubesphere#5841]
**Describe the Bug**
I added an EKS cluster in kubesphere 3.3, and the cluster status keeps prompting **not ready**

`kubefed-controller-manager` logs：

```text
 W0713 01:38:12.971565       1 controller.go:257] Failed to update the status of cluster "tbag": Operation cannot be fulfilled on kubefedclusters.core.kubefed.io "tbag": the object has been modified; please apply your changes to the latest version and try again
 W0713 01:25:21.809098       1 controller.go:257] Failed to update the status of cluster "tbag": Operation cannot be fulfilled on kubefedclusters.core.kubefed.io "tbag": the object has been modified; please apply your changes to the latest version and try again
```

**Versions Used**
master cluster：
    kubesphere：v3.3.2，use kubekey install
    kubernetes：v1.22.12

member cluster（EKS）：
    kubesphere：v3.3.2
    kubernetes：v1.24.15

**Environment**
master cluster:
	CentOS7.9 / 3 master: 8C/16G; 3 nodes: 8C/16G

member cluster(EKS):
	Amazon Linux 2/ t3.medium, 3 nodes

**How To Reproduce**
1. Create EKS
2. Deploy kubesphere v3.3 in eks; refer [here](https://www.kubesphere.io/zh/docs/v3.3/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks/#%E9%85%8D%E7%BD%AE-kubectl)
3. Configure member clusters, `jwtSecret` and `clusterRole`;
4. Get EKS kubeconfig, use follow script(`bash kubeconfig.sh tbag kube-system`):

```bash
#!/bin/bash
# Add user to k8s using service account
if [[ -z "$1" ]] || [[ -z "$2" ]]; then
    echo "usage: $0 <service_account_name> <namespace>"
    exit 1
fi

SERVICE_ACCOUNT_NAME=$1
NAMESPACE="$2"
CLUSTER_ROLE="cluster-admin"
KUBECFG_FILE_NAME="/tmp/kube/k8s-${SERVICE_ACCOUNT_NAME}-${NAMESPACE}-conf"

create_service_account() {
    echo -e "\\nCreating a service account in ${NAMESPACE} namespace: ${SERVICE_ACCOUNT_NAME}"
    kubectl create sa "${SERVICE_ACCOUNT_NAME}" --namespace "${NAMESPACE}"
}

create_cluster_role_binding() {
    echo -e "\\nCreating a cluster role binding: ${SERVICE_ACCOUNT_NAME} and binding to ${CLUSTER_ROLE}"
    kubectl create clusterrolebinding ${SERVICE_ACCOUNT_NAME} --clusterrole=${CLUSTER_ROLE} --serviceaccount=kube-system:${SERVICE_ACCOUNT_NAME}
}

create_secret() {
    echo -e "\\nCreating a secret in ${NAMESPACE} namespace: ${SERVICE_ACCOUNT_NAME}-secret and specify SA as ${SERVICE_ACCOUNT_NAME}"
    kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: ${SERVICE_ACCOUNT_NAME}-secret
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/service-account.name: ${SERVICE_ACCOUNT_NAME}
type: kubernetes.io/service-account-token
EOF
}

create_service_account
create_cluster_role_binding
create_secret

# get TOKEN
TOKEN=`kubectl -n ${NAMESPACE} get secret ${SERVICE_ACCOUNT_NAME}-secret -o jsonpath='{.data.token}' | base64 --decode`

# get CA
CA=`kubectl -n ${NAMESPACE} get secret ${SERVICE_ACCOUNT_NAME}-secret -o jsonpath='{.data.ca\.crt}'`

# get apiServer
API_SERVER=`kubectl config view --minify --raw -o jsonpath='{.clusters[].cluster.server}'`

# set context
echo -e "\\nSet a credentials: ${SERVICE_ACCOUNT_NAME}"
kubectl config set-credentials ${SERVICE_ACCOUNT_NAME} --token=${TOKEN}

echo -e "\\nAdd a user "${SERVICE_ACCOUNT_NAME}" for the current context"
kubectl config set-context --current --user=${SERVICE_ACCOUNT_NAME}

# get kubeconfig to ./${SERVICE_ACCOUNT_NAME}.kubeconfig
echo -e "\\nGenerate kubeconfig file for current context in current dir: ./${SERVICE_ACCOUNT_NAME}.kubeconfig"
kubectl config view --minify --flatten > ./${SERVICE_ACCOUNT_NAME}.kubeconfig
```

The kubeconfig info:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EY3hNakEzTWpneE5sb1hEVE16TURjd09UQTNNamd4Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTlNkCjhnMG5PZUptRVA1dllHZFBBc0Y4K3BGRzA4MXZNLzArTnRUbUFaQ3ZvUW9vRkt6dVFHUnZUbHptUmpTMXpZMWUKenFXSlh3YnFEWlBaMjlNRlBzTjJTUSsyNEc0ditYbEhPZTlPU0RlaFc5YlFnOHBDSVFBR2lMZi9leTNicGpLawpzbERyS0NUd1RNclM4NlplWkZtUmpra1pYWXk1VFlwYnFmK3VzYTFhdkp1QWxiTWRZOE5RR1RNTExuMzdRYlpmCnNzSmpLTXBHOU9pc1dUUDczV1drcEZJN2dNQXlFeUFZTW4yZGVBbmJGT001SDlWVnRxWUs5eHd2YzZieG1naFoKdWpLWkxtRVU0WWpsdDQyOFhuSkU2K2Z4L0pJV25mWGlWMCtNUzdCTHRBRVEySzZSUUhRUzU5cDM3bFkzMW90ZApQd3BRK3pXOFNsbjdLSjJuM1BFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZQdHFxa1Y3NWJlVDYxd1BucUlBTUEwcTkxdXVNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSUEwMUU5d2E3UGJ1VkNmU1haaAoxczB4VE1mZjJCYk4zWlZ5YTR3R0JmbFF6bThDTXhCeWhCT2l0RkQyVFRkUUt0YzZFRjNyVm1JUVFCUjVpcHE4CnVFYUVXb2l1MU9qUkNUN2RTWlVsdit6ODIxQjQvOVFjTWd3ZGhxSzltZEdMSkxsVkpDUVNkakZVRG5XRVVUVkwKSEdRaVhyUXNkc2lzd2toVUQwaTJDY1lObGw3U0NqS3piSzJKSzc5V2wxSi9LaTY0N1F0RzlLSUEyYjlmTTl6VgozNHQxZmp4M1BZOVRtY0lNM3V2Mno3dzNkZ2lEZkk5LzZJMHZGbFJZSTdEMklBOTlPK1EvYWhWRWlXSythRUh5Ck0rek1iMGxUL2lYR05oRG1OY3MrMjhmZWt3Qy9FVFliZTVJWEN6VmJwcVpkcFgyVFk0aFdqV1NzNHRiS0tLeFEKeC93PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://xxxxxxxxx.eks.amazonaws.com
  name: arn:aws:eks:sa-east-1:359992954056:cluster/ks
contexts:
- context:
    cluster: arn:aws:eks:sa-east-1:359992954056:cluster/ks
    user: tbag
  name: arn:aws:eks:sa-east-1:359992954056:cluster/ks
current-context: arn:aws:eks:sa-east-1:359992954056:cluster/ks
kind: Config
preferences: {}
users:
- name: tbag
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InVjaC1EZXhvNk04WmUwRjJ2eFZ6bjJsRWctWmNkdVlmVzJZa2g1T1ZJZFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJ0YmFnLXNlY3JldCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJ0YmFnIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMGU0YjdlNjgtMzQwYi00YzgzLWJhOWQtZmYzMzljOTAyZGMyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOnRiYWcifQ.gvowhJUzRLDSlKenVzfHaVHR1sILwFzPlmf4tmI-cphGhZVFGad3Uw2FlVsSJbElkBNaKM7vjPmMb1Do2ll_NL_QYp2WqPyaECwQbEzDHuxjY5R1URAh6b6P5KkBacimkgjhuji-fDKAqnPDTugae3_hi3SnybOyvR1duvG7RlJhEE52VbuVNjn0x_r6fr8fqC96rX2Q_4LCa5T1-C-KdANpxL-tCNRwiCe_-iaYDH2s_DHV5Z8aE5Bi5QYSDZcWcSPNJQEBP_AkxAISsUb1pTZNNIbSlzMdGP9sLYvSmbSqLuvq5zXiUJCLzEHTSBolWxw4ppDoPOkw-43wUBAnIw
```

> I can get all information of eks cluster through this kubeconfig (using `kubectl` command)

5. Use the generated kubeconfig to perform the add cluster operation in the kubesphere master cluster.

**Expected behavior**
Expect to manage eks through kubesphere, because there are many eks clusters on my side, as well as ack and aks.

![image](https://github.com/kubesphere/kubesphere/assets/139422990/d9045576-6d26-444f-9cfb-d633564bade8)

---

At the beginning, I imported the EKS cluster by referring to the [official documentation](https://www.kubesphere.io/zh/docs/v3.3/multicluster-management/import-cloud-hosted-k8s/import-aws-eks/#%E6%AD%A5%E9%AA%A4-3%E5%88%9B%E5%BB%BA%E6%96%B0%E7%9A%84-kubeconfig-%E6%96%87%E4%BB%B6):

```bash
TOKEN=$(kubectl -n kubesphere-system get secret $(kubectl -n kubesphere-system get sa kubesphere -o jsonpath='{.secrets[0].name}') -o jsonpath='{.data.token}' | base64 -d)

kubectl config set-credentials kubesphere --token=${TOKEN}

kubectl config set-context --current --user=kubesphere
```

but there was a problem with the created kubeconfig. The sa account of kubesphere was not bound to a secret (the token could not be obtained); I don’t know if this is my problem or the official documentation is not clear.
