### ISSUE TITLE
container environment not match between kubesphere terminal and real terminal 

### ISSUE THREAD

**Issue by chenxinlong** [kubesphere/kubesphere#5852]
**Describe the Bug**

Create a deployment with env `env.key.1=env.value.1` inside the pod, yaml as below : 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: test1
  name: test1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
        - name: container-fqgyc9
          imagePullPolicy: IfNotPresent
          image: 'nginx:latest'
          env:
            - name: env.key.1
              value: env.value.1
      serviceAccount: default
      initContainers: []
      volumes: []
      imagePullSecrets: null
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
```

Login to worker node(using ssh) and get the env of this pod like pic below( environment `env.key.1` exists ) : 
![image](https://github.com/kubesphere/kubesphere/assets/9261954/7cc25716-b473-4d5d-a73f-46eb60ae2021)

Connect to container terminal via kubesphere console, execute `env` command under sh or bash like pic below ( environment `env.key.1` not exists ) 

![image](https://github.com/kubesphere/kubesphere/assets/9261954/62fbd8c9-5833-4533-a054-f3b5f5e1f484)

**Versions Used**
KubeSphere: v3.3.0

**Expected behavior**

What I expected is that the environment `env.key.1` exist using terminal provided by kubesphere console
