### ISSUE TITLE
x-forwarded-port=80

### ISSUE THREAD

**Issue by frozonTzh** [kubesphere/kubesphere#5920]
**Describe the Bug**
I deployed a spring security project.Before I log in it will redirect to login page.At this time the port was lost maybe is changed into 80.I add a filter to log all http header.I add the port manuallly then I found x-forwarded-port=80
the full http header  :
```
x-request-id=31bcf82e11888b5eae180b490feedb37, 
content-length=215, 
referer=http://my.host.name:32636/lost-port/login, 
x-forwarded-proto=http, 
accept-language=zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2, 
cookie=JSESSIONID=19D821726ACB1C7D72D13EAE09410191; INGRESSCOOKIE=4d840b75bb440e8f992b093f3ba038dc|e7a92ea442d5798fe3cece72595f4581, 
origin=http://my.host.name:32636, 
x-forwarded-port=80, 
accept=*/*, 
x-real-ip=192.168.1.123, 
x-forwarded-scheme=http, 
x-forwarded-host=my.host.name:32636, 
host=my.host.name:32636, 
content-type=application/json; charset=UTF-8, 
x-scheme=http, 
accept-encoding=gzip, deflate, 
user-agent=Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/117.0
```
 my k8s  file
``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lost-port-app
  labels:
    app: lost-port-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lost-port-app
  template:
    metadata:
      name: lost-port-app
      labels:
        app: lost-port-app
    spec:
      containers:
        - name: lost-port-app
          image: {{.Value.image-name}}
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          ports:
            - containerPort: 8080
      restartPolicy: Always
  ---    
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lost-port-loadbalancer
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - path: /lost-port
            pathType: Prefix
            backend:
              service:
                name: lost-port-service
                port:
                  number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lost-port-service
spec:
  selector:
    app: lost-port-app
  ports:
    - protocol: TCP
      port: 8080
  type: NodePort

```

**Versions Used**
KubeSphere: v3.3.2
Kubernetes: v1.22.12
kubesphere/nginx-ingress-controller:v1.1.0

**Environment**
How many nodes and their hardware configuration:

CentOS Linux release 7.9.2009 (Core) Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz  All-in-One Installation

**Comment by frozonTzh** [comment]
logging filter for log all http header
``` kotlin
@Configuration
open class LoggingFilter : Filter {
    @Throws(IOException::class, ServletException::class)
    override fun doFilter(request: ServletRequest, response: ServletResponse, chain: FilterChain) {
        val httpReq = request as HttpServletRequest
        val url = httpReq.requestURL
            val params = httpReq.parameterMap
            val headerNames = httpReq.headerNames
            val headers: MutableMap<String, String> = HashMap(10)
            while (headerNames.hasMoreElements()) {
                val name = headerNames.nextElement()
                headers[name] = httpReq.getHeader(name)
            }
            logger.warn("receive request {} with headers {}", url, headers)
        chain.doFilter(request, response)
    }

    companion object {
        var logger: Logger = LoggerFactory.getLogger(LoggingFilter::class.java)
    }
}
```

**Comment by weiliang-ms** [comment]
When you log in by accessing the address below：
```
http://192.168.1.1:32222/login
```

redirect to
```
http://192.168.1.1:80/xxxx/xxxxx
```

However, it should be redirected to the following address?

```
http://192.168.1.1:32222/xxxx/xxxxx
```

**Comment by frozonTzh** [comment]
Sorry,Maybe my expression make a misunderstand. In local environment access address below:
``` http://127.0.0.1:8080/lost-port```
then because I don't login.Spring security would redirect to :
``` http://127.0.0.1:8080/lost-port/login```
But now In my kubesphere , access address below:
``` http://my.host.name:32636/lost-port ```
then It redirect to:
``` http://my.host.name/lost-port/login ```
 the port is lost ,maybe disapear or become 80

**Comment by weiliang-ms** [comment]
> Sorry,Maybe my expression make a misunderstand. In local environment access address below: ` http://127.0.0.1:8080/lost-port` then because I don't login.Spring security would redirect to : ` http://127.0.0.1:8080/lost-port/login` But now In my kubesphere , access address below: `http://my.host.name:32636/lost-port` then It redirect to: `http://my.host.name/lost-port/login` the port is lost ,maybe disapear or become 80

> Sorry,Maybe my expression make a misunderstand. In local environment access address below: ` http://127.0.0.1:8080/lost-port` then because I don't login.Spring security would redirect to : ` http://127.0.0.1:8080/lost-port/login` But now In my kubesphere , access address below: `http://my.host.name:32636/lost-port` then It redirect to: `http://my.host.name/lost-port/login` the port is lost ,maybe disapear or become 80


```
# kubectl get gateways.gateway.kubesphere.io -n kubesphere-controls-system -o yaml
apiVersion: v1
items:
- apiVersion: gateway.kubesphere.io/v1alpha1
  kind: Gateway
  metadata:
    annotations:
      kubesphere.io/annotations: ""
      kubesphere.io/creator: admin
    creationTimestamp: "2022-05-16T10:38:52Z"
    finalizers:
    - uninstall-helm-release
    generation: 5
    name: kubesphere-router-kubesphere-system
    namespace: kubesphere-controls-system
    resourceVersion: "466678465"
    uid: 9d08f6c2-1107-448b-9b68-27fea8f39737
  spec:
    controller:
      config:
        compute-full-forwarded-for: "true"
        forwarded-for-header: X-Forwarded-For
        use-forwarded-headers: "true"
        use-port-in-redirects: "true"
        worker-processes: "4"
...
```
`use-port-in-redirects: "true"` might solve your problem

**Comment by frozonTzh** [comment]
Thanks a lot.I tried it ,but it seems not working
``` bash
bash-5.1# kubectl get gateways.gateway.kubesphere.io -n kubesphere-controls-system -o yaml
```
``` yaml
apiVersion: v1
items:
- apiVersion: gateway.kubesphere.io/v1alpha1
  kind: Gateway
  metadata:
    annotations:
      kubesphere.io/annotations: ""
      kubesphere.io/creator: admin
    creationTimestamp: "2023-09-18T06:43:15Z"
    finalizers:
    - uninstall-helm-release
    generation: 6
    name: kubesphere-router-jmix-test
    namespace: kubesphere-controls-system
    resourceVersion: "512695"
    uid: 1329b721-d307-455f-a9b4-0d574a0cf16d
  spec:
    controller:
      config:
        compute-full-forwarded-for: "true"
        forwarded-for-header: X-Forwarded-For
        use-forwarded-headers: "true"
        use-port-in-redirects: "true"
      replicas: 1
...

**Comment by weiliang-ms** [comment]
Have you ever tried publishing your program on a virtual machine?
1. Deploy the program and listen with 8080.
2. Configure the reverse proxy using nginx.
```
server {
      listen 7777;
      location / {
          proxy_pass http://127.0.0.1:8080; 
     }
}
```
3. Access the nginx listening address.
Assume that the VM IP address is `192.168.1.1`
- http://192.168.1.1:7777lost-port

4. Observe the redirect address

http://192.168.1.1:7777lost-port/login 
or 
http://192.168.1.1:8888lost-port/login

If the same problem exists, it is not related to the Ingress.

The following article may help you.

- https://stackoverflow.com/questions/76752290/spring-boot-security-wrong-redirects-using-kubernetes-ingress

**Comment by frozonTzh** [comment]
I tried it  as such config in a docker compose,`http://172.17.0.1` is a ip addr of my local docker network
``` yaml

version: '2'

services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
        - "29000:7777"
    volumes:
        - "./www:/usr/share/nginx/html"
        - "./conf:/etc/nginx/"
        - "./logs:/var/log/nginx"
```
```  
server {
    listen       7777;
    listen  [::]:7777;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location /lost-port {
        proxy_pass   http://172.17.0.1:8080/lost-port;
    }
}

```
I open `http://127.0.0.1:29000/lost-port` then redirect to `http://127.0.0.1:7777/lost-port/login`
and I open `http://172.25.0.2:7777/lost-port/login`(`172.25.0.2` is the ip addr of my docker container),It working well

**Comment by frozonTzh** [comment]
obviously, the port redirected to depend on the nginx listening to

**Comment by weiliang-ms** [comment]
Set the following configuration.
```
server.forward-headers-strategy = native
server.tomcat.redirect-context-root = false
```

for nginx

```
location /lost-port {
        proxy_pass   http://172.17.0.1:8080/lost-port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

refer to https://github.com/spring-projects/spring-boot/issues/22908

**Comment by frozonTzh** [comment]
It seems also not working.And after change port in browser address manually,There is no X-Forwarded header in log.

**Comment by weiliang-ms** [comment]
> It seems also not working.And after change port in browser address manually,There is no X-Forwarded header in log.

If it is convenient to provide a remote tool, troubleshoot the problem.
Email to linweiliang94@gmail.com

**Comment by frozonTzh** [comment]
Because of current environment in local network, Let me rent a server in internet and redeploy it

**Comment by frozonTzh** [comment]
The configuration send from tzh1234@gmail.com ,thanks a lot.And all of the code of lost port was at https://github.com/frozonTzh/lostedport

**Comment by weiliang-ms** [comment]
When I follow the following configuration, everything is fine.
```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: lost-port-loadbalancer
  namespace: test
  annotations:
    kubesphere.io/creator: admin
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/affinity-mode: persistent
    nginx.ingress.kubernetes.io/proxy-redirect-from: 'http://x.x.x.x.nip.io'
    nginx.ingress.kubernetes.io/proxy-redirect-to: 'http://x.x.x.x.nip.io:32333'
    nginx.ingress.kubernetes.io/session-cookie-expires: '172800'
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-max-age: '172800'
spec:
  rules:
    - host: x.x.x.x.nip.io
      http:
        paths:
          - path: /lost-port
            pathType: ImplementationSpecific
            backend:
              service:
                name: lost-port-service
                port:
                  number: 8080
```

I think it is still related to the backend service getting the Host value wrong.
