### ISSUE TITLE
devops-argo-applicationset-controller image cmd error

### ISSUE THREAD

**Issue by brook-w** [kubesphere/kubesphere#5982]
# 1. Env
-  kubernetes 1.26.5
-  kubesphere 3.4.1/3.4.0
-  kubekey 3.0.13
# 2. ERROR
devops compoment error

image: argocd-applicationset-controller not have `application-controller` cmd
```
...
  containers:
    - name: applicationset-controller
      image: 'hub.instack.cloud/argoproj/argocd-applicationset:v0.4.1'
      command:
        - application-controller
        - '--metrics-addr=:8080'
        - '--probe-addr=:8081'
        - '--namespace=argocd'
        - '--argocd-repo-server=devops-argocd-repo-server:8081'
        - '--policy=sync'
        - '--debug=false'
        - '--dry-run=false'
        
...
```
this command exec not success
beacuse not have `application-controller` cmd
![image](https://github.com/kubesphere/kubesphere/assets/42824702/73c7044d-0fb2-47fa-b26e-59572b050d38)
![image](https://github.com/kubesphere/kubesphere/assets/42824702/b2be322a-8c88-4708-bb7f-8781cb1c2071)
