### ISSUE TITLE
change the project to member cluster in the workspace after setting the member Cluster Visibility, comes out a error: "会话已超时或用户已从其他地方登录，请重新登录。"

### ISSUE THREAD

**Issue by lianghuiyuan** [kubesphere/kubesphere#6002]
**Describe the Bug**
After add cluster member into the host cluster, then change the member Cluster Visibility to a Workspace, Everythings seems ok, but when you in the 「workspace」- 「Project」 to exchange the cluster, you will see "会话已超时或用户已从其他地方登录，请重新登录。" error.

- host cluster: 
  kubesphere: 3.4.0
  kubernetes: v1.23.8-r10-23.2.19.3
  nodes: 1 master node, 5 worker nodes

- member cluster:
  kubesphere: 3.4.0
  kubernetes: v1.26.7
  nodes: 1 master node, 2 worker nodes

**Environment**
Ubuntu 22.04

```
# uname -a
Linux mec-master-01 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**How To Reproduce**
- step1: 
set member Cluster Visibility

<img width="1654" alt="image" src="https://github.com/kubesphere/kubesphere/assets/8090998/3217c78d-09be-43b1-b664-e0d7f3063ea3">

set member Cluster Visibility success,  ***but the list of workspaces is empty*** .
<img width="1646" alt="image" src="https://github.com/kubesphere/kubesphere/assets/8090998/88149848-1bc7-4aab-aa53-dab1dce024b2">

and you will get to see one more cluster Visibility in the workspace,

<img width="815" alt="image" src="https://github.com/kubesphere/kubesphere/assets/8090998/f6dd7bca-b337-4232-bfba-b188532c1374">

- step2: 
  Login kubesphere with an account which not ‘admin’，
<img width="474" alt="image" src="https://github.com/kubesphere/kubesphere/assets/8090998/10b2e8ef-220c-473e-9d37-a8d8a2b97dbb">

 change the cluster to the member cluster, then see the error: "会话已超时或用户已从其他地方登录，请重新登录。"
<img width="1389" alt="image" src="https://github.com/kubesphere/kubesphere/assets/8090998/e2c9f98f-1a25-4ff7-b6c9-dd15b7ad8365">

**Expected behavior**
no errors.

**Comment by lianghuiyuan** [comment]
same promblems: https://ask.kubesphere.io/forum/d/7394-kubesphere-member

**Comment by lianghuiyuan** [comment]
kubefed fix: controller-manager panic when kubeconfig set filed insecure-skip-tls-verify : https://github.com/kubernetes-retired/kubefed/pull/1505

But kubesphere seems not Update the version of kubefed controller: https://github.com/kubesphere/kubesphere/issues/4891

**Comment by lianghuiyuan** [comment]
处理办法：
1. 加入到 host 主集群的 member 集群的 kubeconfig 中不要使用`insecure-skip-tls-verify=true`，直接使用 ca.crt 证书(base64)：`certificate-authority-data: {BASE64 STRING}`。    eg:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <`cat /etc/kubernetes/pki/ca.crt | base64`>
    server: https://<ip>:6443
  name: cluster.local
contexts:
- context:
    cluster: cluster.local
    user: kubernetes-admin
  name: kubernetes-admin@cluster.local
current-context: kubernetes-admin@cluster.local
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: xxxxxxxxxxx
    client-key-data: xxxxxxxxxx

```
2. 在 host 集群中，重启`kubefed-admission-webhook` 和 `kubefed-controller-manager` 两个服务：
- 将kubefed-admission-webhook deployment 中的 replica 配置为 0 后再配置为 1
- 将kubefed-controller-manager deployment 中的 replica 配置为 0 后再配置为 2
