### ISSUE TITLE
Fluentbit-operator  not working - CrashLoopBackOff - KubeSphere v3.3.2 / jaeger-secret not found error - KubeSphere v3.4.1

### ISSUE THREAD

**Issue by halil-bugol** [kubesphere/kubesphere#6020]
Fluentbit operator keeps crashing and restarting. After updating to version 3.4.1, the error goes away. But this time we get an error in Jaeger.

![image](https://github.com/kubesphere/kubesphere/assets/60687576/943272f7-e092-4ab5-a317-bd983788178a)

Jaeger stopped working properly after the upgrade. Query and collector give CreateContainerConfigError. After describing, we try describe pods and get a jaeger-secret not found error.

![image](https://github.com/kubesphere/kubesphere/assets/60687576/9f87a1de-361b-4344-ae4a-357d2691fe3d)

As far as I know, jaeger-secret contains ES-USERNAME and PASSWORD values. When we create this secret manually and enter a value, the log screens in the KubeSphere interface show the logs as 0 and do not work.

Next, we set the es - basicauth value to true in the clusterconfiguration.yaml file, gave the username and password, added it to the jeager-secret file and redeployed it to ks-installer. It didn't work again.

How we can solve this problem. Is this a bug?

**Comment by zheng1** [comment]
Can you `describe` this pod? Let's take a look at these pod events.

**Comment by Gebitily7** [comment]
```
Name:         jaeger-collector-6f4dc875f-784lv
Namespace:    istio-system
Priority:     0
Node:         ecs3/192.168.2.87
Start Time:   Tue, 09 Jan 2024 14:34:36 +0800
Labels:       app=jaeger
              app.kubernetes.io/component=collector
              app.kubernetes.io/instance=jaeger
              app.kubernetes.io/managed-by=jaeger-operator
              app.kubernetes.io/name=jaeger-collector
              app.kubernetes.io/part-of=jaeger
              pod-template-hash=6f4dc875f
Annotations:  cni.projectcalico.org/containerID: 21a6aa5aab5c6a070ba4e02957a26383d5518a9a020facfbb6a6646499a271af
              cni.projectcalico.org/podIP: 10.233.90.113/32
              cni.projectcalico.org/podIPs: 10.233.90.113/32
              linkerd.io/inject: disabled
              prometheus.io/port: 14269
              prometheus.io/scrape: true
              sidecar.istio.io/inject: false
Status:       Pending
IP:           10.233.90.113
IPs:
  IP:           10.233.90.113
Controlled By:  ReplicaSet/jaeger-collector-6f4dc875f
Containers:
  jaeger-collector:
    Container ID:
    Image:         registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-collector:1.29
    Image ID:
    Ports:         9411/TCP, 14267/TCP, 14268/TCP, 14269/TCP, 14250/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    Args:
      --es.index-prefix=logstash
      --es.server-urls=http://elasticsearch-logging-data.kubesphere-logging-system.svc:9200
      --sampling.strategies-file=/etc/jaeger/sampling/sampling.json
    State:          Waiting
      Reason:       CreateContainerConfigError
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:      20m
      memory:   50Mi
    Liveness:   http-get http://:14269/ delay=5s timeout=1s period=15s #success=1 #failure=5
    Readiness:  http-get http://:14269/ delay=1s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      jaeger-secret  Secret  Optional: false
    Environment:
      SPAN_STORAGE_TYPE:           elasticsearch
      COLLECTOR_ZIPKIN_HOST_PORT:  :9411
    Mounts:
      /etc/jaeger/sampling from jaeger-sampling-configuration-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rx2j9 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  jaeger-sampling-configuration-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      jaeger-sampling-configuration
    Optional:  false
  kube-api-access-rx2j9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  18m                  default-scheduler  Successfully assigned istio-system/jaeger-collector-6f4dc875f-784lv to ecs3
  Warning  Failed     16m (x12 over 18m)   kubelet            Error: secret "jaeger-secret" not found
  Normal   Pulled     3m9s (x73 over 18m)  kubelet            Container image "registry.cn-beijing.aliyuncs.com/kubesphereio/jaeger-collector:1.29" already present on machine
```
@zheng1

**Comment by zheng1** [comment]
@pixiake @hongzhouzi PTAL

**Comment by hongzhouzi** [comment]
Can you show the configuration of the ES account password configured in **ClusterConfiguration**? jeager secrets will be generated in this way during installation, it is possible that your configuration code cannot handle it well.

https://github.com/kubesphere/ks-installer/blob/v3.4.1/roles/ks-istio/tasks/jaeger-install.yaml#L22-L56

**Comment by Gebitily7** [comment]
Replace ES with OpenSearch and it's working.

**Comment by Gebitily7** [comment]
```
apiVersion: installer.kubesphere.io/v1alpha1
kind: ClusterConfiguration
metadata:
  labels:
    version: v3.4.1
  name: ks-installer
  namespace: kubesphere-system
spec:
  alerting:
    enabled: true
  auditing:
    enabled: false
  authentication:
    jwtSecret: ''
  common:
    core:
      console:
        enableMultiLogin: true
        port: 30880
        type: NodePort
    es:
      enabled: false
    gpu:
      kinds:
        - default: true
          resourceName: nvidia.com/gpu
          resourceType: GPU
    minio:
      volumeSize: 20Gi
    monitoring:
      GPUMonitoring:
        enabled: false
      endpoint: 'http://prometheus-operated.kubesphere-monitoring-system.svc:9090'
    openldap:
      enabled: false
    opensearch:
      basicAuth:
        enabled: true
        password: password # your password
        username: username # your username
      dashboard:
        enabled: true
      data:
        volumeSize: 20Gi
      enabled: true
      logMaxAge: '7'
      master:
        volumeSize: 4Gi
      opensearchPrefix: whizard
    redis:
      enabled: false
  devops:
    enabled: false
    jenkinsMemoryLim: 8Gi
    jenkinsMemoryReq: 4Gi
    jenkinsVolumeSize: 8Gi
  edgeruntime:
    enabled: false
    kubeedge:
      cloudCore:
        cloudHub:
          advertiseAddress:
            - ''
        service:
          cloudhubHttpsNodePort: '30002'
          cloudhubNodePort: '30000'
          cloudhubQuicNodePort: '30001'
          cloudstreamNodePort: '30003'
          tunnelNodePort: '30004'
      enabled: false
      iptables-manager:
        enabled: true
        mode: external
  etcd:
    endpointIps: 192.168.7.1
    monitoring: true
    port: 2379
    tlsEnable: true
  events:
    enabled: true
    ruler:
      enabled: true
      replicas: 2
  logging:
    enabled: true
    logsidecar:
      enabled: true
      replicas: 2
  metrics_server:
    enabled: false
  monitoring:
    gpu:
      nvidia_dcgm_exporter:
        enabled: false
    node_exporter:
      port: 9100
    storageClass: ''
  multicluster:
    clusterRole: none
  network:
    ippool:
      type: none
    networkpolicy:
      enabled: false
    topology:
      type: none
  openpitrix:
    store:
      enabled: false
  persistence:
    storageClass: ''
  servicemesh:
    enabled: true
    istio:
      components:
        cni:
          enabled: false
        ingressGateways:
          - enabled: false
            name: istio-ingressgateway
  terminal:
    timeout: 600
  zone: cn
status:
  alerting:
    enabledTime: '2023-12-29T18:04:47CST'
    status: enabled
  clusterId: a3331613-6816-4166-86d9-4699f995eae7-1688053151
  core:
    enabledTime: '2024-01-09T17:34:05CST'
    status: enabled
    version: v3.4.1
  events:
    enabledTime: '2023-12-29T18:03:58CST'
    ruler:
      enabledTime: '2023-12-29T18:03:58CST'
      status: enabled
    status: enabled
  fluentbit:
    enabledTime: '2023-12-29T18:02:54CST'
    status: enabled
  logging:
    enabledTime: '2024-01-09T17:07:49CST'
    status: enabled
  monitoring:
    enabledTime: '2024-01-09T17:34:50CST'
    status: enabled
  opensearch:
    enabledTime: '2024-01-09T17:06:50CST'
    status: enabled
  servicemesh:
    enabledTime: '2024-01-09T17:34:29CST'
    status: enabled
```
