### ISSUE TITLE
CAS 协议无法正确重定向登录页面

### ISSUE THREAD

**Issue by leshalv** [kubesphere/kubesphere#6044]
以下为CAS协议配置，kubesphere无法正确在casServerURL配置后拼接/login地址，如果 casServerURL 配置为cas login全路径，ticket验证时，将又会出现访问地址不正确问题。

```yaml
      accessTokenMaxAge: 1h
      accessTokenInactivityTimeout: 30m
      identityProviders:
      - name: topiam
        type: CASIdentityProvider
        mappingMethod: auto
        provider:
          redirectURL: "http://xxxxxxx:30880/oauth/redirect/topiam"
          casServerURL: "http://xxxxxxx:1989/api/v1/authorize/cas/yxebe3fbtz8k9potvxs8a1gp5xupqm7e"
          insecureSkipVerify: true
```
