### ISSUE TITLE
kubesphere v3.4.1  notifcation not work

### ISSUE THREAD

**Issue by ElfenSterben** [kubesphere/kubesphere#6247]
**Versions Used**
KubeSphere: v3.4.1
Kubernetes: v1.27.4
notification-manager:v2.3.0

![image](https://github.com/user-attachments/assets/9a7112c4-c95b-42ad-ba36-331fdbcbc54d)

I set the notifcation on website with feishu webhook url, test return success,but the feishu bot get nothing。
![image](https://github.com/user-attachments/assets/3887d271-cbe0-4b53-a42b-19608f9fa9f8)

then i try to create recevier with kubectl 
```
apiVersion: notification.kubesphere.io/v2beta2
kind: Receiver
metadata:
  name: global-receiver
  labels:
    type: global
spec:
  feishu:
    chatbot:
      webhook:
        value: https://open.feishu.cn/open-apis/bot/v2/hook/xxxxxx
    enabled: true
    template: nm.feishu.post
    tmplType: text
    tmplText:
      name: notification-manager-template
      namespace: kubesphere-monitoring-system
```
after apply it,i find that the CRD was cleaned
![image](https://github.com/user-attachments/assets/4e09124c-344d-4ed9-b28e-919a96d0fb40)
