### ISSUE TITLE
OIDC Logout Redirect to end_session_endpoint Not Working

### ISSUE THREAD

**Issue by GH-00** [kubesphere/kubesphere#6347]
**Versions Used**

KubeSphere: v4.1.2
Kubernetes: v1.28
OIDC Provider: Keycloak 

**Describe the Bug**

When using OpenID Connect (OIDC) for authentication in KubeSphere, the logout functionality does not redirect properly to the end_session_endpoint URL provided by the Identity Provider (IdP).

I would like the logout button to directly redirect to the end_session_endpoint URL, as shown in the attached images. Is it possible to achieve this by modifying the KubeSphere secret or configuration files, or does it require changes in the KubeSphere source code?
</br>
When I press the logout button,

![Image](https://github.com/user-attachments/assets/8ca65c79-300e-4c18-8069-3a0bf3ddaa2c)

The end_session_endpoint URL returned:

![Image](https://github.com/user-attachments/assets/3f41768d-9cb6-4081-a4c4-710154a3d9e3)

</br>

**How To Reproduce**

This is my secret for configuring keycloak.

```
name: keycloak
type: OIDCIdentityProvider
mappingMethod: auto
provider:
  idTokenSkipVerify: true
  insecureSkipVerify: true
  scopes:
    - openid
    - email
    - profile
    - projects
  clientID: '{client_id}'
  clientSecret: '{secret}'
  issuer: 'https://{keycloak_ip}/realms/{realm}'
  redirectURL: 'http://{kubesphere_ip}/oauth/redirect/keycloak' 
```
