### ISSUE TITLE
kubesphere ldap groupSearchBase dosn't work

### ISSUE THREAD

**Issue by cc901109** [kubesphere/kubesphere#6468]
Follow up official document to set up,
and I add groupSearchBase in it,
but I think it's dosn't work

```
apiVersion: v1
kind: Secret
metadata:
  namespace: kubesphere-system
  name: identity-provider-ldap
  labels:
    config.kubesphere.io/type: identityprovider
stringData:
  configuration.yaml: |
    name: openldap
    type: LDAPIdentityProvider
    mappingMethod: auto
    provider:
      host: "192.168.0.2:389"
      managerDN: uid=root,cn=users,dc=nas
      managerPassword: "********"
      userSearchBase: cn=users,dc=nas
      loginAttribute: uid
      mailAttribute: mail
      groupSearchBase: OU=xxx,OU=Service xx,DC=xxx
type: config.kubesphere.io/identityprovider
```

How to fix it?
