### ISSUE TITLE
3.3.2版本的kubesphere是不支持arm吗

### ISSUE THREAD

**Issue by john1337** [kubesphere/kubesphere#6480]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report installation issues. For general usage questions you can refer to [KubeSphere Documentation](https://kubesphere.io/docs) or join our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE)

**What's your question**

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

ubuntu20.04

**Error logs or message (Attach logs or screenshot)**
安装完kubesphere后发现有的容器启动失败了，看了下用到了kubesphereio/defaultbackend-amd64:1.4这个镜像，很明显这个镜像是不能在arm上运行的

**Installer Version**
v3.3.2

**Comment by besscroft** [comment]
Supported! You need to manually change `defaultbackend-amd64` to `defaultbackend-arm`.

example:

```yaml
spec:
  replicas: 1
    spec:
      containers:
        - name: default-http-backend
          image: 'mirrorgooglecontainers/defaultbackend-arm:1.4'
```

> Actually, using different names to distinguish between architectures isn't the best approach. A more reasonable method is to use a unified name and support multi-architecture images.
