### ISSUE TITLE
ks-apiserver health check 403 after upgrading from 4.1.2 -> 4.1.3

### ISSUE THREAD

**Issue by Imccccc** [kubesphere/kubesphere#6521]
**Describe the Bug**

After upgrading kubesphere version, the ks-apiserver keep restart. From log, it shows the health check fail with status 403.
I found the helm report success but the ks-apiserver images does not upgrade successfully. In deployment, the version shows 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    meta.helm.sh/release-name: ks-core
    meta.helm.sh/release-namespace: kubesphere-system
  creationTimestamp: "2024-11-29T14:34:45Z"
  generation: 10
  labels:
    app: ks-apiserver
    app.kubernetes.io/managed-by: Helm
    version: v4.1.3
....
      containers:
      - command:
        - ks-apiserver
        - --logtostderr=true
        image: docker.io/kubesphere/ks-apiserver:v4.1.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /livez
            port: 9090
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: ks-apiserver
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 20m
            memory: 100Mi

```

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere: from 4.1.2 to 4.1.3
Kubernetes: (If KubeSphere installer used, you can skip this) 1.31.0

**Environment**
How many nodes and their hardware configuration:
AWS EKS

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**
