### ISSUE TITLE
我想单独部署监控部分可以吗

### ISSUE THREAD

**Issue by liuts** [kubesphere/kubesphere#710]
[备注]: <> (请补全下面信息，帮助我们更快地定位问题。提交问题前预览下issue，看下是否有格式错误)

**问题描述**
我想单独部署监控部分，可以实现吗？应该怎么做
**安装环境的硬件配置**
centos7.5
[备注]: <> (请说明节点的运行环境，是否是物理机，云主机，VMware虚拟机)

**错误信息或截图**

**Installer版本**

**Comment by huanggze** [comment]
```yaml
# 修改 ks-apiserver 的启动命令
kubectl edit deployments -n kubesphere-system ks-apiserver

# 添加运行参数 prometheus-endpoint 与  secondary-prometheus-endpoint
# 改成你自己的地址
apiVersion: extensions/v1beta1
kind: Deployment
  metadata:
    ...
spec:
  ...
  containers:
  - name: ks-apiserver      
     command:
     - ks-apiserver
     - --prometheus-endpoint=http://prometheus-k8s.kubesphere-monitoring-system.svc:9090/api/v1/
     - --secondary-prometheus-endpoint=http://prometheus-k8s-system.kubesphere-monitoring-system.svc:9090/api/v1/

# 把 recordingrules 加入到你的 Prometheus
kubectl get prometheusrules.monitoring.coreos.com  -n kubesphere-monitoring-system prometheus-k8s-rules -oyaml
```

注：prometheus-endpoint 对应的 Prometheus 实例必须包含 ServiceMonitor 类型资源 kube-state-metrics、node-exporter、kubelet；secondary-prometheus-endpoint 对应的实例必须包含 etcd、apiserver、kube-scheduler
```shell
# 内置默认的 prometheus-endpoint
kubectl get prometheus  -n kubesphere-monitoring-system k8s -oyaml

# 内置默认的 secondary-prometheus-endpoint
kubectl get prometheus  -n kubesphere-monitoring-system k8s-system -oyaml
```
